"""Qualifier ↔ Claude CLI session inbox bridge (PR-Q2).

Once :class:`app.qualifier.qualifier_service.QualifierService` decides an
event is ``NON_ROUTINE``, it must be surfaced to the per-scope Claude CLI
session that owns the resolved ``target_scope``. The session might or
might not be running at that moment — the broker spawns it lazily on the
next chat turn — so we can't rely on the in-memory ``in_queue`` alone.

This module implements both halves of the bridge:

* :func:`persist_hint` writes a :class:`QualifierHint` row into
  ``claude_scratchpad`` (``namespace='inbox'``) with a unique ``hint_id``
  key. The session bootstrap brief points Claude at
  ``scratchpad_query(scope=..., namespace='inbox')`` so a fresh session
  picks it up at cold start.
* :func:`push_into_live_session` pushes a ``[qualifier-hint] ...`` system
  message into the running session's ``out_queue`` so the next LLM turn
  surfaces it as part of the chat — same pattern as the existing
  ``[agent-update]`` AgentJobStateChanged subscriber.

The persistent path is the source of truth (idempotent on replay /
crash); the live push is purely a latency optimisation. URGENT events
that miss both (no live session AND no Claude reasoning before deadline)
fall back to the ad-hoc consult path in :class:`QualifierService`.
"""

from __future__ import annotations

import datetime
import logging
import uuid
from dataclasses import asdict, dataclass

from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase

from app.config import settings

logger = logging.getLogger(__name__)


# Mongo singleton — mirrors the pattern in compact_store / audit / rules
# (one motor client per process, lazily constructed). We don't share with
# those modules because each owns its own client by convention.
_mongo: AsyncIOMotorClient | None = None


def _db() -> AsyncIOMotorDatabase:
    global _mongo
    if _mongo is None:
        _mongo = AsyncIOMotorClient(settings.mongodb_url)
    return _mongo.get_default_database()


def _utc_now() -> datetime.datetime:
    return datetime.datetime.now(datetime.timezone.utc)


# Body preview cap — keeps inbox rows small even when the qualifier sees
# huge mails / transcripts. Claude can always re-fetch the full event via
# the appropriate MCP tool (``o365_mail_read``, ``get_meeting_transcript``)
# once the hint orients it on which event matters.
_BODY_PREVIEW_CHARS = 2000
_SUBJECT_PREVIEW_CHARS = 200

# TTL applied on the scratchpad row. Hints handled by the session call
# ``scratchpad_delete`` explicitly; this is the safety net for hints the
# session never gets to.
_HINT_TTL_DAYS = 14


@dataclass
class QualifierHint:
    """Persistent payload Claude CLI session reads from inbox.

    Generated by qualifier on every NON_ROUTINE event. Stored in
    ``claude_scratchpad`` (scope=target, namespace=inbox) so a session
    that's not running yet picks it up at lazy spawn via the bootstrap
    ``scratchpad_query`` call.
    """

    hint_id: str           # uuid
    source_kind: str
    sender: str
    subject: str
    body: str              # truncated to ~2000 chars
    classification: str
    urgency: str           # low / normal / high / urgent
    rationale: str
    detected_client_id: str | None
    detected_project_id: str | None
    target_scope: str      # client:<cid> or project:<cid>:<pid>
    ts: str                # ISO 8601


async def persist_hint(target_scope: str, hint: QualifierHint) -> None:
    """Idempotent INSERT into ``claude_scratchpad``.

    Each hint has a unique ``hint_id`` key so concurrent emits don't
    collide. The unique index is ``(scope, namespace, key)`` per
    :func:`app.sessions.compact_store.ensure_indexes`, so ``insert_one``
    is naturally idempotent on replay (DuplicateKeyError swallowed).
    """
    try:
        now = _utc_now()
        doc = {
            "scope": target_scope,
            "namespace": "inbox",
            "key": hint.hint_id,
            "data": {**asdict(hint)},
            "tags": [
                "qualifier",
                "hint",
                hint.urgency.lower(),
                hint.classification.lower(),
            ],
            "ttl_days": _HINT_TTL_DAYS,
            "created_at": now,
            "updated_at": now,
        }
        await _db()["claude_scratchpad"].insert_one(doc)
    except Exception as exc:
        # Persistence is the source of truth, but a swallowed write must
        # never break the qualifier hot path. Log + continue; the live
        # push (if a session is running) still gets the hint.
        logger.warning(
            "persist_hint failed | scope=%s hint_id=%s err=%s",
            target_scope, hint.hint_id, exc,
        )


async def push_into_live_session(target_scope: str, hint: QualifierHint) -> bool:
    """Inject a ``[qualifier-hint]`` system message into a running session.

    If a live session for ``target_scope`` exists, push the hint summary
    onto its ``out_queue`` so the next LLM turn boundary surfaces it as
    part of the chat — same pattern as the existing
    ``[agent-update]`` AgentJobStateChanged subscriber.

    Returns ``True`` if pushed, ``False`` if no live session (or the push
    failed) — caller may then fall back to the URGENT consult path.
    """
    from app.sessions.session_broker import session_broker

    session = session_broker.get_session(target_scope)
    if session is None or session.stop_flag.is_set():
        return False

    msg = (
        f"[qualifier-hint] {hint.urgency.upper()} {hint.classification} "
        f"from {hint.sender} (source={hint.source_kind}): "
        f"{hint.subject[:120]}"
    )
    try:
        session.out_queue.put_nowait({
            "type": "system",
            "content": msg,
            "metadata": {
                "kind": "qualifier_hint",
                "hintId": hint.hint_id,
                "urgency": hint.urgency,
                "classification": hint.classification,
                "sender": hint.sender,
                "scope": target_scope,
            },
        })
        return True
    except Exception:
        logger.warning(
            "push_into_live_session: out_queue full or rejected | scope=%s",
            target_scope,
        )
        return False


def truncate_body(body: str) -> str:
    """Public helper so :class:`QualifierService` builds hints with the
    same ceiling the storage layer enforces."""
    return body[:_BODY_PREVIEW_CHARS]


def truncate_subject(subject: str) -> str:
    return subject[:_SUBJECT_PREVIEW_CHARS]


def new_hint_id() -> str:
    """Module-local helper so callers don't import :mod:`uuid` just for this."""
    return str(uuid.uuid4())
