package com.jervis.service.brain

import com.jervis.dto.brain.BrainIssueType
import com.jervis.dto.brain.ConfluenceSpaceSection
import com.jervis.integration.wiki.WikiPage
import mu.KotlinLogging
import org.springframework.stereotype.Service

/**
 * EPIC 16: Brain Workflow Structure.
 *
 * S1: Maps BrainIssueType to JIRA issue types (with Czech locale support).
 * S2: Auto-creates Confluence space hierarchy using ConfluenceSpaceSection enum.
 */
@Service
class BrainWorkflowService(
    private val brainWriteService: BrainWriteService,
) {
    private val logger = KotlinLogging.logger {}

    /**
     * E16-S1: Map BrainIssueType to the JIRA issue type string.
     * Czech Jira uses localized names.
     */
    fun resolveIssueTypeName(type: BrainIssueType): String = when (type) {
        BrainIssueType.TASK -> "Task"
        BrainIssueType.BUG -> "Bug"
        BrainIssueType.FINDING -> "Task"  // No separate "Finding" type — use Task with label
        BrainIssueType.REVIEW -> "Task"   // Same — use Task with "review" label
        BrainIssueType.LEARNING -> "Task" // Same — use Task with "learning" label
    }

    /**
     * E16-S1: Get labels for a BrainIssueType.
     * Used to distinguish Finding/Review/Learning within Task type.
     */
    fun resolveLabels(type: BrainIssueType): List<String> = when (type) {
        BrainIssueType.TASK -> emptyList()
        BrainIssueType.BUG -> emptyList()
        BrainIssueType.FINDING -> listOf("finding", "monitoring")
        BrainIssueType.REVIEW -> listOf("review", "code-review")
        BrainIssueType.LEARNING -> listOf("learning", "best-practice")
    }

    /**
     * E16-S1: Create a brain issue with proper type enforcement.
     */
    suspend fun createTypedIssue(
        type: BrainIssueType,
        summary: String,
        description: String? = null,
        priority: String? = null,
        extraLabels: List<String> = emptyList(),
    ) = brainWriteService.createIssue(
        summary = summary,
        description = description,
        issueType = resolveIssueTypeName(type),
        priority = priority,
        labels = resolveLabels(type) + extraLabels,
    )

    /**
     * E16-S2: Ensure Confluence space hierarchy exists.
     * Creates top-level pages for each ConfluenceSpaceSection if missing.
     */
    suspend fun ensureSpaceStructure(): Map<ConfluenceSpaceSection, WikiPage> {
        if (!brainWriteService.isConfigured()) {
            logger.warn { "Brain not configured, skipping space structure creation" }
            return emptyMap()
        }

        val result = mutableMapOf<ConfluenceSpaceSection, WikiPage>()

        for (section in ConfluenceSpaceSection.entries) {
            val title = sectionTitle(section)
            try {
                // Check if page already exists
                val existing = brainWriteService.searchPages(
                    query = "title = \"$title\"",
                    maxResults = 1,
                )
                if (existing.isNotEmpty()) {
                    result[section] = existing.first()
                    logger.debug { "Space section '$title' already exists (${existing.first().id})" }
                } else {
                    val page = brainWriteService.createPage(
                        title = title,
                        content = sectionDescription(section),
                    )
                    result[section] = page
                    logger.info { "Created brain space section: '$title' (${page.id})" }
                }
            } catch (e: Exception) {
                logger.warn(e) { "Failed to ensure space section '$title'" }
            }
        }

        return result
    }

    /**
     * E16-S2: Get Confluence page title for a section.
     */
    fun sectionTitle(section: ConfluenceSpaceSection): String = when (section) {
        ConfluenceSpaceSection.ARCHITECTURE -> "Architecture"
        ConfluenceSpaceSection.DAILY_REPORTS -> "Daily Reports"
        ConfluenceSpaceSection.CLIENT_PAGES -> "Clients"
        ConfluenceSpaceSection.KNOWLEDGE -> "Knowledge"
        ConfluenceSpaceSection.DRAFTS -> "Drafts"
    }

    private fun sectionDescription(section: ConfluenceSpaceSection): String = when (section) {
        ConfluenceSpaceSection.ARCHITECTURE -> "<p>Architecture decisions and design documents.</p>"
        ConfluenceSpaceSection.DAILY_REPORTS -> "<p>Automated daily activity reports generated by Jervis.</p>"
        ConfluenceSpaceSection.CLIENT_PAGES -> "<p>Per-client documentation and notes.</p>"
        ConfluenceSpaceSection.KNOWLEDGE -> "<p>Learned procedures and best practices.</p>"
        ConfluenceSpaceSection.DRAFTS -> "<p>Work-in-progress documents.</p>"
    }
}
