# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/whisper/transcribe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/whisper/transcribe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fjervis/whisper/transcribe.proto\x12\x0ejervis.whisper\x1a\x19jervis/common/types.proto\"\x88\x01\n\x11TranscribeRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x14\n\x0coptions_json\x18\x04 \x01(\t\x12\x10\n\x08\x62lob_ref\x18\x05 \x01(\t\"3\n\x0fTranscribeEvent\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x11\n\tdata_json\x18\x02 \x01(\t\";\n\rHealthRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\"R\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0cmodel_loaded\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x04 \x01(\t\"?\n\x11GpuReleaseRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\"&\n\x12GpuReleaseResponse\x12\x10\n\x08released\x18\x01 \x01(\x08\x32\x82\x02\n\x0eWhisperService\x12R\n\nTranscribe\x12!.jervis.whisper.TranscribeRequest\x1a\x1f.jervis.whisper.TranscribeEvent0\x01\x12G\n\x06Health\x12\x1d.jervis.whisper.HealthRequest\x1a\x1e.jervis.whisper.HealthResponse\x12S\n\nGpuRelease\x12!.jervis.whisper.GpuReleaseRequest\x1a\".jervis.whisper.GpuReleaseResponseB.\n\x1c\x63om.jervis.contracts.whisperB\x0cWhisperProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.whisper.transcribe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.jervis.contracts.whisperB\014WhisperProtoP\001'
  _globals['_TRANSCRIBEREQUEST']._serialized_start=79
  _globals['_TRANSCRIBEREQUEST']._serialized_end=215
  _globals['_TRANSCRIBEEVENT']._serialized_start=217
  _globals['_TRANSCRIBEEVENT']._serialized_end=268
  _globals['_HEALTHREQUEST']._serialized_start=270
  _globals['_HEALTHREQUEST']._serialized_end=329
  _globals['_HEALTHRESPONSE']._serialized_start=331
  _globals['_HEALTHRESPONSE']._serialized_end=413
  _globals['_GPURELEASEREQUEST']._serialized_start=415
  _globals['_GPURELEASEREQUEST']._serialized_end=478
  _globals['_GPURELEASERESPONSE']._serialized_start=480
  _globals['_GPURELEASERESPONSE']._serialized_end=518
  _globals['_WHISPERSERVICE']._serialized_start=521
  _globals['_WHISPERSERVICE']._serialized_end=779
# @@protoc_insertion_point(module_scope)
