package com.jervis.dto

enum class PendingTaskTypeEnum {
    EMAIL_PROCESSING,
    FILE_PROCESSING,
    JIRA_PROCESSING,
    LINK_PROCESSING,
    CONFLUENCE_PROCESSING,
    ANALYSIS_PROCESSING,
    SCHEDULED_PROCESSING,

    // Direct input from a user
    USER_INPUT_PROCESSING,
    DATA_PROCESSING,
}
