# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.orchestrator import chat_pb2 as jervis_dot_orchestrator_dot_chat__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/orchestrator/chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorChatServiceStub(object):
    """OrchestratorChatService — foreground chat pipeline. Chat is a
    server-streaming RPC that yields agentic-loop events (token, tool_call,
    tool_result, approval_request, done, error). Approve + Stop are unary
    control RPCs over the same session.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/jervis.orchestrator.OrchestratorChatService/Chat',
                request_serializer=jervis_dot_orchestrator_dot_chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_chat__pb2.ChatEvent.FromString,
                _registered_method=True)
        self.ApproveAction = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorChatService/ApproveAction',
                request_serializer=jervis_dot_orchestrator_dot_chat__pb2.ApproveActionRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_chat__pb2.ApproveActionAck.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorChatService/Stop',
                request_serializer=jervis_dot_orchestrator_dot_chat__pb2.StopChatRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_chat__pb2.StopChatAck.FromString,
                _registered_method=True)


class OrchestratorChatServiceServicer(object):
    """OrchestratorChatService — foreground chat pipeline. Chat is a
    server-streaming RPC that yields agentic-loop events (token, tool_call,
    tool_result, approval_request, done, error). Approve + Stop are unary
    control RPCs over the same session.
    """

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=jervis_dot_orchestrator_dot_chat__pb2.ChatRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_chat__pb2.ChatEvent.SerializeToString,
            ),
            'ApproveAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveAction,
                    request_deserializer=jervis_dot_orchestrator_dot_chat__pb2.ApproveActionRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_chat__pb2.ApproveActionAck.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=jervis_dot_orchestrator_dot_chat__pb2.StopChatRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_chat__pb2.StopChatAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.orchestrator.OrchestratorChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.orchestrator.OrchestratorChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorChatService(object):
    """OrchestratorChatService — foreground chat pipeline. Chat is a
    server-streaming RPC that yields agentic-loop events (token, tool_call,
    tool_result, approval_request, done, error). Approve + Stop are unary
    control RPCs over the same session.
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jervis.orchestrator.OrchestratorChatService/Chat',
            jervis_dot_orchestrator_dot_chat__pb2.ChatRequest.SerializeToString,
            jervis_dot_orchestrator_dot_chat__pb2.ChatEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorChatService/ApproveAction',
            jervis_dot_orchestrator_dot_chat__pb2.ApproveActionRequest.SerializeToString,
            jervis_dot_orchestrator_dot_chat__pb2.ApproveActionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorChatService/Stop',
            jervis_dot_orchestrator_dot_chat__pb2.StopChatRequest.SerializeToString,
            jervis_dot_orchestrator_dot_chat__pb2.StopChatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
