# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.orchestrator import companion_pb2 as jervis_dot_orchestrator_dot_companion__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/orchestrator/companion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorCompanionServiceStub(object):
    """OrchestratorCompanionService — persistent Claude companion sessions.
    Adhoc dispatch was removed with slice V3-cleanup (no pod-to-pod
    consumer existed; the internal orchestrator graph still uses
    `companion_runner.dispatch_adhoc` directly, not over gRPC).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorCompanionService/StartSession',
                request_serializer=jervis_dot_orchestrator_dot_companion__pb2.SessionStartRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_companion__pb2.SessionStartResponse.FromString,
                _registered_method=True)
        self.SessionEvent = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorCompanionService/SessionEvent',
                request_serializer=jervis_dot_orchestrator_dot_companion__pb2.SessionEventRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_companion__pb2.SessionEventAck.FromString,
                _registered_method=True)
        self.StopSession = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorCompanionService/StopSession',
                request_serializer=jervis_dot_orchestrator_dot_companion__pb2.SessionRef.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_companion__pb2.SessionAck.FromString,
                _registered_method=True)
        self.StreamSession = channel.unary_stream(
                '/jervis.orchestrator.OrchestratorCompanionService/StreamSession',
                request_serializer=jervis_dot_orchestrator_dot_companion__pb2.StreamSessionRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_companion__pb2.OutboxEvent.FromString,
                _registered_method=True)


class OrchestratorCompanionServiceServicer(object):
    """OrchestratorCompanionService — persistent Claude companion sessions.
    Adhoc dispatch was removed with slice V3-cleanup (no pod-to-pod
    consumer existed; the internal orchestrator graph still uses
    `companion_runner.dispatch_adhoc` directly, not over gRPC).
    """

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorCompanionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=jervis_dot_orchestrator_dot_companion__pb2.SessionStartRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_companion__pb2.SessionStartResponse.SerializeToString,
            ),
            'SessionEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionEvent,
                    request_deserializer=jervis_dot_orchestrator_dot_companion__pb2.SessionEventRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_companion__pb2.SessionEventAck.SerializeToString,
            ),
            'StopSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSession,
                    request_deserializer=jervis_dot_orchestrator_dot_companion__pb2.SessionRef.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_companion__pb2.SessionAck.SerializeToString,
            ),
            'StreamSession': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSession,
                    request_deserializer=jervis_dot_orchestrator_dot_companion__pb2.StreamSessionRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_companion__pb2.OutboxEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.orchestrator.OrchestratorCompanionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.orchestrator.OrchestratorCompanionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorCompanionService(object):
    """OrchestratorCompanionService — persistent Claude companion sessions.
    Adhoc dispatch was removed with slice V3-cleanup (no pod-to-pod
    consumer existed; the internal orchestrator graph still uses
    `companion_runner.dispatch_adhoc` directly, not over gRPC).
    """

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorCompanionService/StartSession',
            jervis_dot_orchestrator_dot_companion__pb2.SessionStartRequest.SerializeToString,
            jervis_dot_orchestrator_dot_companion__pb2.SessionStartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorCompanionService/SessionEvent',
            jervis_dot_orchestrator_dot_companion__pb2.SessionEventRequest.SerializeToString,
            jervis_dot_orchestrator_dot_companion__pb2.SessionEventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorCompanionService/StopSession',
            jervis_dot_orchestrator_dot_companion__pb2.SessionRef.SerializeToString,
            jervis_dot_orchestrator_dot_companion__pb2.SessionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jervis.orchestrator.OrchestratorCompanionService/StreamSession',
            jervis_dot_orchestrator_dot_companion__pb2.StreamSessionRequest.SerializeToString,
            jervis_dot_orchestrator_dot_companion__pb2.OutboxEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
