# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.orchestrator import control_pb2 as jervis_dot_orchestrator_dot_control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/orchestrator/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorControlServiceStub(object):
    """OrchestratorControlService — thread-level control RPCs over the
    LangGraph-backed orchestrator. Long-running orchestration events flow
    over the KbProgress / OrchestratorProgress callbacks already migrated
    in Phase 1; this service covers the short-payload control surface.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorControlService/Health',
                request_serializer=jervis_dot_orchestrator_dot_control__pb2.HealthRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_control__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorControlService/GetStatus',
                request_serializer=jervis_dot_orchestrator_dot_control__pb2.StatusRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_control__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Approve = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorControlService/Approve',
                request_serializer=jervis_dot_orchestrator_dot_control__pb2.ApproveRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_control__pb2.ApproveAck.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorControlService/Cancel',
                request_serializer=jervis_dot_orchestrator_dot_control__pb2.ThreadRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_control__pb2.CancelAck.FromString,
                _registered_method=True)
        self.Interrupt = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorControlService/Interrupt',
                request_serializer=jervis_dot_orchestrator_dot_control__pb2.ThreadRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_control__pb2.InterruptAck.FromString,
                _registered_method=True)


class OrchestratorControlServiceServicer(object):
    """OrchestratorControlService — thread-level control RPCs over the
    LangGraph-backed orchestrator. Long-running orchestration events flow
    over the KbProgress / OrchestratorProgress callbacks already migrated
    in Phase 1; this service covers the short-payload control surface.
    """

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Approve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interrupt(self, request, context):
        """Resume helper left out of the initial surface — no Kotlin consumer
        dials it today (Approve already handles the resume-after-interrupt
        flow). Add back if a new caller needs a dedicated resume RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=jervis_dot_orchestrator_dot_control__pb2.HealthRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_control__pb2.HealthResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=jervis_dot_orchestrator_dot_control__pb2.StatusRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_control__pb2.StatusResponse.SerializeToString,
            ),
            'Approve': grpc.unary_unary_rpc_method_handler(
                    servicer.Approve,
                    request_deserializer=jervis_dot_orchestrator_dot_control__pb2.ApproveRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_control__pb2.ApproveAck.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=jervis_dot_orchestrator_dot_control__pb2.ThreadRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_control__pb2.CancelAck.SerializeToString,
            ),
            'Interrupt': grpc.unary_unary_rpc_method_handler(
                    servicer.Interrupt,
                    request_deserializer=jervis_dot_orchestrator_dot_control__pb2.ThreadRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_control__pb2.InterruptAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.orchestrator.OrchestratorControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.orchestrator.OrchestratorControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorControlService(object):
    """OrchestratorControlService — thread-level control RPCs over the
    LangGraph-backed orchestrator. Long-running orchestration events flow
    over the KbProgress / OrchestratorProgress callbacks already migrated
    in Phase 1; this service covers the short-payload control surface.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorControlService/Health',
            jervis_dot_orchestrator_dot_control__pb2.HealthRequest.SerializeToString,
            jervis_dot_orchestrator_dot_control__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorControlService/GetStatus',
            jervis_dot_orchestrator_dot_control__pb2.StatusRequest.SerializeToString,
            jervis_dot_orchestrator_dot_control__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Approve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorControlService/Approve',
            jervis_dot_orchestrator_dot_control__pb2.ApproveRequest.SerializeToString,
            jervis_dot_orchestrator_dot_control__pb2.ApproveAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorControlService/Cancel',
            jervis_dot_orchestrator_dot_control__pb2.ThreadRequest.SerializeToString,
            jervis_dot_orchestrator_dot_control__pb2.CancelAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interrupt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorControlService/Interrupt',
            jervis_dot_orchestrator_dot_control__pb2.ThreadRequest.SerializeToString,
            jervis_dot_orchestrator_dot_control__pb2.InterruptAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
