# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.orchestrator import dashboard_pb2 as jervis_dot_orchestrator_dot_dashboard__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/orchestrator/dashboard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorDashboardServiceStub(object):
    """OrchestratorDashboardService — read-only snapshot of the SessionBroker
    (active Claude sessions, LRU cap, pause state, agent-job holds, recent
    LRU evictions). Consumed by the Kotlin server which fronts a kRPC
    push-flow surface for the desktop UI Dashboard screen.

    Unary for now: server pulls every 5 s into a MutableSharedFlow(replay=1)
    and the UI subscribes to that flow. A future upgrade to server-streaming
    keyed off broker audit writes is possible without changing the kRPC
    contract.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSessionSnapshot = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorDashboardService/GetSessionSnapshot',
                request_serializer=jervis_dot_orchestrator_dot_dashboard__pb2.GetSessionSnapshotRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_dashboard__pb2.SessionSnapshotResponse.FromString,
                _registered_method=True)


class OrchestratorDashboardServiceServicer(object):
    """OrchestratorDashboardService — read-only snapshot of the SessionBroker
    (active Claude sessions, LRU cap, pause state, agent-job holds, recent
    LRU evictions). Consumed by the Kotlin server which fronts a kRPC
    push-flow surface for the desktop UI Dashboard screen.

    Unary for now: server pulls every 5 s into a MutableSharedFlow(replay=1)
    and the UI subscribes to that flow. A future upgrade to server-streaming
    keyed off broker audit writes is possible without changing the kRPC
    contract.
    """

    def GetSessionSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorDashboardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSessionSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionSnapshot,
                    request_deserializer=jervis_dot_orchestrator_dot_dashboard__pb2.GetSessionSnapshotRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_dashboard__pb2.SessionSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.orchestrator.OrchestratorDashboardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.orchestrator.OrchestratorDashboardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorDashboardService(object):
    """OrchestratorDashboardService — read-only snapshot of the SessionBroker
    (active Claude sessions, LRU cap, pause state, agent-job holds, recent
    LRU evictions). Consumed by the Kotlin server which fronts a kRPC
    push-flow surface for the desktop UI Dashboard screen.

    Unary for now: server pulls every 5 s into a MutableSharedFlow(replay=1)
    and the UI subscribes to that flow. A future upgrade to server-streaming
    keyed off broker audit writes is possible without changing the kRPC
    contract.
    """

    @staticmethod
    def GetSessionSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorDashboardService/GetSessionSnapshot',
            jervis_dot_orchestrator_dot_dashboard__pb2.GetSessionSnapshotRequest.SerializeToString,
            jervis_dot_orchestrator_dot_dashboard__pb2.SessionSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
