# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/orchestrator/dashboard.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/orchestrator/dashboard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#jervis/orchestrator/dashboard.proto\x12\x13jervis.orchestrator\x1a\x19jervis/common/types.proto\"G\n\x19GetSessionSnapshotRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\"\xec\x02\n\x17SessionSnapshotResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63tive_count\x18\x03 \x01(\x05\x12\x0b\n\x03\x63\x61p\x18\x04 \x01(\x05\x12\x0e\n\x06paused\x18\x05 \x01(\x08\x12\x34\n\x08sessions\x18\x06 \x03(\x0b\x32\".jervis.orchestrator.ActiveSession\x12X\n\x0f\x61gent_job_holds\x18\x07 \x03(\x0b\x32?.jervis.orchestrator.SessionSnapshotResponse.AgentJobHoldsEntry\x12=\n\x10recent_evictions\x18\x08 \x03(\x0b\x32#.jervis.orchestrator.EvictionRecord\x1a\x34\n\x12\x41gentJobHoldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc9\x01\n\rActiveSession\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x12\n\nproject_id\x18\x04 \x01(\t\x12\x19\n\x11\x63umulative_tokens\x18\x05 \x01(\x05\x12\x14\n\x0cidle_seconds\x18\x06 \x01(\x05\x12\x1b\n\x13\x63ompact_in_progress\x18\x07 \x01(\x08\x12 \n\x18last_compact_age_seconds\x18\x08 \x01(\x05\";\n\x0e\x45victionRecord\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\t2\x92\x01\n\x1cOrchestratorDashboardService\x12r\n\x12GetSessionSnapshot\x12..jervis.orchestrator.GetSessionSnapshotRequest\x1a,.jervis.orchestrator.SessionSnapshotResponseBA\n!com.jervis.contracts.orchestratorB\x1aOrchestratorDashboardProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.orchestrator.dashboard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.jervis.contracts.orchestratorB\032OrchestratorDashboardProtoP\001'
  _globals['_SESSIONSNAPSHOTRESPONSE_AGENTJOBHOLDSENTRY']._loaded_options = None
  _globals['_SESSIONSNAPSHOTRESPONSE_AGENTJOBHOLDSENTRY']._serialized_options = b'8\001'
  _globals['_GETSESSIONSNAPSHOTREQUEST']._serialized_start=87
  _globals['_GETSESSIONSNAPSHOTREQUEST']._serialized_end=158
  _globals['_SESSIONSNAPSHOTRESPONSE']._serialized_start=161
  _globals['_SESSIONSNAPSHOTRESPONSE']._serialized_end=525
  _globals['_SESSIONSNAPSHOTRESPONSE_AGENTJOBHOLDSENTRY']._serialized_start=473
  _globals['_SESSIONSNAPSHOTRESPONSE_AGENTJOBHOLDSENTRY']._serialized_end=525
  _globals['_ACTIVESESSION']._serialized_start=528
  _globals['_ACTIVESESSION']._serialized_end=729
  _globals['_EVICTIONRECORD']._serialized_start=731
  _globals['_EVICTIONRECORD']._serialized_end=790
  _globals['_ORCHESTRATORDASHBOARDSERVICE']._serialized_start=793
  _globals['_ORCHESTRATORDASHBOARDSERVICE']._serialized_end=939
# @@protoc_insertion_point(module_scope)
