# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/orchestrator/dispatch.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/orchestrator/dispatch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"jervis/orchestrator/dispatch.proto\x12\x13jervis.orchestrator\x1a\x19jervis/common/types.proto\"d\n\x0f\x44ispatchRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\"@\n\x0b\x44ispatchAck\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tthread_id\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t2\xc7\x01\n\x1bOrchestratorDispatchService\x12Q\n\x07Qualify\x12$.jervis.orchestrator.DispatchRequest\x1a .jervis.orchestrator.DispatchAck\x12U\n\x0bOrchestrate\x12$.jervis.orchestrator.DispatchRequest\x1a .jervis.orchestrator.DispatchAckB@\n!com.jervis.contracts.orchestratorB\x19OrchestratorDispatchProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.orchestrator.dispatch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.jervis.contracts.orchestratorB\031OrchestratorDispatchProtoP\001'
  _globals['_DISPATCHREQUEST']._serialized_start=86
  _globals['_DISPATCHREQUEST']._serialized_end=186
  _globals['_DISPATCHACK']._serialized_start=188
  _globals['_DISPATCHACK']._serialized_end=252
  _globals['_ORCHESTRATORDISPATCHSERVICE']._serialized_start=255
  _globals['_ORCHESTRATORDISPATCHSERVICE']._serialized_end=454
# @@protoc_insertion_point(module_scope)
