# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.orchestrator import graph_pb2 as jervis_dot_orchestrator_dot_graph__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/orchestrator/graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorGraphServiceStub(object):
    """OrchestratorGraphService — AgentGraph lookup + idle maintenance
    trigger. Administrative vertex CRUD (delete/update/create/cleanup/
    purge-stale) stays on FastAPI until a cross-service consumer dials
    it (UI path goes through Kotlin kRPC, not this servicer).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTaskGraph = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorGraphService/GetTaskGraph',
                request_serializer=jervis_dot_orchestrator_dot_graph__pb2.GetTaskGraphRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_graph__pb2.TaskGraphResponse.FromString,
                _registered_method=True)
        self.RunMaintenance = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorGraphService/RunMaintenance',
                request_serializer=jervis_dot_orchestrator_dot_graph__pb2.MaintenanceRunRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_graph__pb2.MaintenanceRunResult.FromString,
                _registered_method=True)
        self.DeleteVertex = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorGraphService/DeleteVertex',
                request_serializer=jervis_dot_orchestrator_dot_graph__pb2.VertexIdRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_graph__pb2.VertexMutationAck.FromString,
                _registered_method=True)
        self.UpdateVertex = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorGraphService/UpdateVertex',
                request_serializer=jervis_dot_orchestrator_dot_graph__pb2.UpdateVertexRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_graph__pb2.VertexMutationAck.FromString,
                _registered_method=True)
        self.CreateVertex = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorGraphService/CreateVertex',
                request_serializer=jervis_dot_orchestrator_dot_graph__pb2.CreateVertexRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_graph__pb2.VertexMutationAck.FromString,
                _registered_method=True)
        self.ForceCleanup = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorGraphService/ForceCleanup',
                request_serializer=jervis_dot_orchestrator_dot_graph__pb2.CleanupRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_graph__pb2.CleanupResult.FromString,
                _registered_method=True)
        self.PurgeStale = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorGraphService/PurgeStale',
                request_serializer=jervis_dot_orchestrator_dot_graph__pb2.PurgeStaleRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_graph__pb2.PurgeStaleResult.FromString,
                _registered_method=True)
        self.MemorySearch = channel.unary_unary(
                '/jervis.orchestrator.OrchestratorGraphService/MemorySearch',
                request_serializer=jervis_dot_orchestrator_dot_graph__pb2.MemorySearchRequest.SerializeToString,
                response_deserializer=jervis_dot_orchestrator_dot_graph__pb2.MemorySearchResult.FromString,
                _registered_method=True)


class OrchestratorGraphServiceServicer(object):
    """OrchestratorGraphService — AgentGraph lookup + idle maintenance
    trigger. Administrative vertex CRUD (delete/update/create/cleanup/
    purge-stale) stays on FastAPI until a cross-service consumer dials
    it (UI path goes through Kotlin kRPC, not this servicer).
    """

    def GetTaskGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunMaintenance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVertex(self, request, context):
        """Memory graph admin — used by UI proxy path through the Kotlin server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVertex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVertex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceCleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeStale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemorySearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTaskGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskGraph,
                    request_deserializer=jervis_dot_orchestrator_dot_graph__pb2.GetTaskGraphRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_graph__pb2.TaskGraphResponse.SerializeToString,
            ),
            'RunMaintenance': grpc.unary_unary_rpc_method_handler(
                    servicer.RunMaintenance,
                    request_deserializer=jervis_dot_orchestrator_dot_graph__pb2.MaintenanceRunRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_graph__pb2.MaintenanceRunResult.SerializeToString,
            ),
            'DeleteVertex': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVertex,
                    request_deserializer=jervis_dot_orchestrator_dot_graph__pb2.VertexIdRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_graph__pb2.VertexMutationAck.SerializeToString,
            ),
            'UpdateVertex': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVertex,
                    request_deserializer=jervis_dot_orchestrator_dot_graph__pb2.UpdateVertexRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_graph__pb2.VertexMutationAck.SerializeToString,
            ),
            'CreateVertex': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVertex,
                    request_deserializer=jervis_dot_orchestrator_dot_graph__pb2.CreateVertexRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_graph__pb2.VertexMutationAck.SerializeToString,
            ),
            'ForceCleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceCleanup,
                    request_deserializer=jervis_dot_orchestrator_dot_graph__pb2.CleanupRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_graph__pb2.CleanupResult.SerializeToString,
            ),
            'PurgeStale': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeStale,
                    request_deserializer=jervis_dot_orchestrator_dot_graph__pb2.PurgeStaleRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_graph__pb2.PurgeStaleResult.SerializeToString,
            ),
            'MemorySearch': grpc.unary_unary_rpc_method_handler(
                    servicer.MemorySearch,
                    request_deserializer=jervis_dot_orchestrator_dot_graph__pb2.MemorySearchRequest.FromString,
                    response_serializer=jervis_dot_orchestrator_dot_graph__pb2.MemorySearchResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.orchestrator.OrchestratorGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.orchestrator.OrchestratorGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorGraphService(object):
    """OrchestratorGraphService — AgentGraph lookup + idle maintenance
    trigger. Administrative vertex CRUD (delete/update/create/cleanup/
    purge-stale) stays on FastAPI until a cross-service consumer dials
    it (UI path goes through Kotlin kRPC, not this servicer).
    """

    @staticmethod
    def GetTaskGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorGraphService/GetTaskGraph',
            jervis_dot_orchestrator_dot_graph__pb2.GetTaskGraphRequest.SerializeToString,
            jervis_dot_orchestrator_dot_graph__pb2.TaskGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunMaintenance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorGraphService/RunMaintenance',
            jervis_dot_orchestrator_dot_graph__pb2.MaintenanceRunRequest.SerializeToString,
            jervis_dot_orchestrator_dot_graph__pb2.MaintenanceRunResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVertex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorGraphService/DeleteVertex',
            jervis_dot_orchestrator_dot_graph__pb2.VertexIdRequest.SerializeToString,
            jervis_dot_orchestrator_dot_graph__pb2.VertexMutationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVertex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorGraphService/UpdateVertex',
            jervis_dot_orchestrator_dot_graph__pb2.UpdateVertexRequest.SerializeToString,
            jervis_dot_orchestrator_dot_graph__pb2.VertexMutationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVertex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorGraphService/CreateVertex',
            jervis_dot_orchestrator_dot_graph__pb2.CreateVertexRequest.SerializeToString,
            jervis_dot_orchestrator_dot_graph__pb2.VertexMutationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceCleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorGraphService/ForceCleanup',
            jervis_dot_orchestrator_dot_graph__pb2.CleanupRequest.SerializeToString,
            jervis_dot_orchestrator_dot_graph__pb2.CleanupResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeStale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorGraphService/PurgeStale',
            jervis_dot_orchestrator_dot_graph__pb2.PurgeStaleRequest.SerializeToString,
            jervis_dot_orchestrator_dot_graph__pb2.PurgeStaleResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemorySearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.orchestrator.OrchestratorGraphService/MemorySearch',
            jervis_dot_orchestrator_dot_graph__pb2.MemorySearchRequest.SerializeToString,
            jervis_dot_orchestrator_dot_graph__pb2.MemorySearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
