# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/orchestrator/graph.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/orchestrator/graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fjervis/orchestrator/graph.proto\x12\x13jervis.orchestrator\x1a\x19jervis/common/types.proto\"e\n\x13GetTaskGraphRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\"6\n\x11TaskGraphResponse\x12\x12\n\ngraph_json\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"e\n\x15MaintenanceRunRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\r\n\x05phase\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\t\"\xc8\x01\n\x14MaintenanceRunResult\x12\r\n\x05phase\x18\x01 \x01(\x05\x12\x13\n\x0bmem_removed\x18\x02 \x01(\x05\x12\x18\n\x10thinking_evicted\x18\x03 \x01(\x05\x12\x13\n\x0blqm_drained\x18\x04 \x01(\x05\x12\x18\n\x10\x61\x66\x66\x61irs_archived\x18\x05 \x01(\x05\x12\x1e\n\x16next_client_for_phase2\x18\x06 \x01(\t\x12\x11\n\tclient_id\x18\x07 \x01(\t\x12\x10\n\x08\x66indings\x18\x08 \x03(\t2\xe5\x01\n\x18OrchestratorGraphService\x12`\n\x0cGetTaskGraph\x12(.jervis.orchestrator.GetTaskGraphRequest\x1a&.jervis.orchestrator.TaskGraphResponse\x12g\n\x0eRunMaintenance\x12*.jervis.orchestrator.MaintenanceRunRequest\x1a).jervis.orchestrator.MaintenanceRunResultB=\n!com.jervis.contracts.orchestratorB\x16OrchestratorGraphProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.orchestrator.graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.jervis.contracts.orchestratorB\026OrchestratorGraphProtoP\001'
  _globals['_GETTASKGRAPHREQUEST']._serialized_start=83
  _globals['_GETTASKGRAPHREQUEST']._serialized_end=184
  _globals['_TASKGRAPHRESPONSE']._serialized_start=186
  _globals['_TASKGRAPHRESPONSE']._serialized_end=240
  _globals['_MAINTENANCERUNREQUEST']._serialized_start=242
  _globals['_MAINTENANCERUNREQUEST']._serialized_end=343
  _globals['_MAINTENANCERUNRESULT']._serialized_start=346
  _globals['_MAINTENANCERUNRESULT']._serialized_end=546
  _globals['_ORCHESTRATORGRAPHSERVICE']._serialized_start=549
  _globals['_ORCHESTRATORGRAPHSERVICE']._serialized_end=778
# @@protoc_insertion_point(module_scope)
