# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/orchestrator/job_logs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/orchestrator/job_logs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"jervis/orchestrator/job_logs.proto\x12\x13jervis.orchestrator\x1a\x19jervis/common/types.proto\"M\n\x0eJobLogsRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x0f\n\x07task_id\x18\x02 \x01(\t\":\n\x0bJobLogEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04tool\x18\x03 \x01(\t2s\n\x1aOrchestratorJobLogsService\x12U\n\nStreamLogs\x12#.jervis.orchestrator.JobLogsRequest\x1a .jervis.orchestrator.JobLogEvent0\x01\x42?\n!com.jervis.contracts.orchestratorB\x18OrchestratorJobLogsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.orchestrator.job_logs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.jervis.contracts.orchestratorB\030OrchestratorJobLogsProtoP\001'
  _globals['_JOBLOGSREQUEST']._serialized_start=86
  _globals['_JOBLOGSREQUEST']._serialized_end=163
  _globals['_JOBLOGEVENT']._serialized_start=165
  _globals['_JOBLOGEVENT']._serialized_end=223
  _globals['_ORCHESTRATORJOBLOGSSERVICE']._serialized_start=225
  _globals['_ORCHESTRATORJOBLOGSSERVICE']._serialized_end=340
# @@protoc_insertion_point(module_scope)
