# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/orchestrator/voice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/orchestrator/voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fjervis/orchestrator/voice.proto\x12\x13jervis.orchestrator\x1a\x19jervis/common/types.proto\"\xf5\x01\n\x13VoiceProcessRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\x12\x12\n\nproject_id\x18\x05 \x01(\t\x12\x10\n\x08group_id\x18\x06 \x01(\t\x12\x0b\n\x03tts\x18\x07 \x01(\x08\x12\x12\n\nmeeting_id\x18\x08 \x01(\t\x12\x13\n\x0blive_assist\x18\t \x01(\x08\x12\x13\n\x0b\x63hunk_index\x18\n \x01(\x05\x12\x10\n\x08is_final\x18\x0b \x01(\x08\"4\n\x10VoiceStreamEvent\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x11\n\tdata_json\x18\x02 \x01(\t\"s\n\x10VoiceHintRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x12\n\nproject_id\x18\x04 \x01(\t\"!\n\x11VoiceHintResponse\x12\x0c\n\x04hint\x18\x01 \x01(\t2\xcf\x01\n\x18OrchestratorVoiceService\x12\\\n\x07Process\x12(.jervis.orchestrator.VoiceProcessRequest\x1a%.jervis.orchestrator.VoiceStreamEvent0\x01\x12U\n\x04Hint\x12%.jervis.orchestrator.VoiceHintRequest\x1a&.jervis.orchestrator.VoiceHintResponseB=\n!com.jervis.contracts.orchestratorB\x16OrchestratorVoiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.orchestrator.voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.jervis.contracts.orchestratorB\026OrchestratorVoiceProtoP\001'
  _globals['_VOICEPROCESSREQUEST']._serialized_start=84
  _globals['_VOICEPROCESSREQUEST']._serialized_end=329
  _globals['_VOICESTREAMEVENT']._serialized_start=331
  _globals['_VOICESTREAMEVENT']._serialized_end=383
  _globals['_VOICEHINTREQUEST']._serialized_start=385
  _globals['_VOICEHINTREQUEST']._serialized_end=500
  _globals['_VOICEHINTRESPONSE']._serialized_start=502
  _globals['_VOICEHINTRESPONSE']._serialized_end=535
  _globals['_ORCHESTRATORVOICESERVICE']._serialized_start=538
  _globals['_ORCHESTRATORVOICESERVICE']._serialized_end=745
# @@protoc_insertion_point(module_scope)
