# Local profile configuration
# Use this profile when running Qdrant and MongoDB locally
# Activate with: --spring.profiles.active=local

spring:
  data:
    mongodb:
      # For local development, use URI without authentication
      # This overrides all individual properties from main application.yml
      uri: mongodb://localhost:27017/jervis

# Qdrant vector database configuration for local development
qdrant:
  host: localhost
  port: 6334

# Override logging for local development if needed
logging:
  level:
    com.jervis: DEBUG
    root: INFO