# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.knowledgebase import ingest_pb2 as jervis_dot_knowledgebase_dot_ingest__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/knowledgebase/ingest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeIngestServiceStub(object):
    """KnowledgeIngestService — content ingestion into KB (RAG chunks +
    graph nodes). FullIngest variants carry the main text inline; binary
    attachments travel over the blob side channel (PUT /blob/kb-doc/{id})
    and are referenced via AttachmentRef.blob_ref.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/Ingest',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.FromString,
                _registered_method=True)
        self.IngestImmediate = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/IngestImmediate',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.FromString,
                _registered_method=True)
        self.IngestQueue = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/IngestQueue',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestQueueAck.FromString,
                _registered_method=True)
        self.IngestFile = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/IngestFile',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestFileRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.FromString,
                _registered_method=True)
        self.IngestFull = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/IngestFull',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.FullIngestRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.FullIngestResult.FromString,
                _registered_method=True)
        self.IngestFullAsync = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/IngestFullAsync',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.AsyncFullIngestRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.AsyncIngestAck.FromString,
                _registered_method=True)
        self.IngestGitStructure = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/IngestGitStructure',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.GitStructureIngestRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.GitStructureIngestResult.FromString,
                _registered_method=True)
        self.IngestGitCommits = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/IngestGitCommits',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.GitCommitIngestRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.GitCommitIngestResult.FromString,
                _registered_method=True)
        self.IngestCpg = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/IngestCpg',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.CpgIngestRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.CpgIngestResult.FromString,
                _registered_method=True)
        self.Crawl = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/Crawl',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.CrawlRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.FromString,
                _registered_method=True)
        self.Purge = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeIngestService/Purge',
                request_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.PurgeRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.PurgeResult.FromString,
                _registered_method=True)


class KnowledgeIngestServiceServicer(object):
    """KnowledgeIngestService — content ingestion into KB (RAG chunks +
    graph nodes). FullIngest variants carry the main text inline; binary
    attachments travel over the blob side channel (PUT /blob/kb-doc/{id})
    and are referenced via AttachmentRef.blob_ref.
    """

    def Ingest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestImmediate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestFull(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestFullAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestGitStructure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestGitCommits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestCpg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Crawl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Purge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeIngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.SerializeToString,
            ),
            'IngestImmediate': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestImmediate,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.SerializeToString,
            ),
            'IngestQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestQueue,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestQueueAck.SerializeToString,
            ),
            'IngestFile': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestFile,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestFileRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.SerializeToString,
            ),
            'IngestFull': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestFull,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.FullIngestRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.FullIngestResult.SerializeToString,
            ),
            'IngestFullAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestFullAsync,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.AsyncFullIngestRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.AsyncIngestAck.SerializeToString,
            ),
            'IngestGitStructure': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestGitStructure,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.GitStructureIngestRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.GitStructureIngestResult.SerializeToString,
            ),
            'IngestGitCommits': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestGitCommits,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.GitCommitIngestRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.GitCommitIngestResult.SerializeToString,
            ),
            'IngestCpg': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestCpg,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.CpgIngestRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.CpgIngestResult.SerializeToString,
            ),
            'Crawl': grpc.unary_unary_rpc_method_handler(
                    servicer.Crawl,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.CrawlRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.SerializeToString,
            ),
            'Purge': grpc.unary_unary_rpc_method_handler(
                    servicer.Purge,
                    request_deserializer=jervis_dot_knowledgebase_dot_ingest__pb2.PurgeRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_ingest__pb2.PurgeResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.knowledgebase.KnowledgeIngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.knowledgebase.KnowledgeIngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeIngestService(object):
    """KnowledgeIngestService — content ingestion into KB (RAG chunks +
    graph nodes). FullIngest variants carry the main text inline; binary
    attachments travel over the blob side channel (PUT /blob/kb-doc/{id})
    and are referenced via AttachmentRef.blob_ref.
    """

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/Ingest',
            jervis_dot_knowledgebase_dot_ingest__pb2.IngestRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestImmediate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/IngestImmediate',
            jervis_dot_knowledgebase_dot_ingest__pb2.IngestRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/IngestQueue',
            jervis_dot_knowledgebase_dot_ingest__pb2.IngestRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.IngestQueueAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/IngestFile',
            jervis_dot_knowledgebase_dot_ingest__pb2.IngestFileRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestFull(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/IngestFull',
            jervis_dot_knowledgebase_dot_ingest__pb2.FullIngestRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.FullIngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestFullAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/IngestFullAsync',
            jervis_dot_knowledgebase_dot_ingest__pb2.AsyncFullIngestRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.AsyncIngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestGitStructure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/IngestGitStructure',
            jervis_dot_knowledgebase_dot_ingest__pb2.GitStructureIngestRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.GitStructureIngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestGitCommits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/IngestGitCommits',
            jervis_dot_knowledgebase_dot_ingest__pb2.GitCommitIngestRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.GitCommitIngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestCpg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/IngestCpg',
            jervis_dot_knowledgebase_dot_ingest__pb2.CpgIngestRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.CpgIngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Crawl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/Crawl',
            jervis_dot_knowledgebase_dot_ingest__pb2.CrawlRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.IngestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Purge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeIngestService/Purge',
            jervis_dot_knowledgebase_dot_ingest__pb2.PurgeRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_ingest__pb2.PurgeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
