# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.knowledgebase import retrieve_pb2 as jervis_dot_knowledgebase_dot_retrieve__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/knowledgebase/retrieve_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeRetrieveServiceStub(object):
    """KnowledgeRetrieveService — vector + graph hybrid retrieval over the KB.
    Read-side RPCs only; ingestion lives in ingest.proto, graph walks live
    in graph.proto.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeRetrieveService/Retrieve',
                request_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.RetrievalRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.EvidencePack.FromString,
                _registered_method=True)
        self.RetrieveSimple = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeRetrieveService/RetrieveSimple',
                request_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.RetrievalRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.EvidencePack.FromString,
                _registered_method=True)
        self.RetrieveHybrid = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeRetrieveService/RetrieveHybrid',
                request_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.HybridRetrievalRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.HybridEvidencePack.FromString,
                _registered_method=True)
        self.AnalyzeCode = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeRetrieveService/AnalyzeCode',
                request_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.TraversalRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.JoernAnalyzeResult.FromString,
                _registered_method=True)
        self.JoernScan = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeRetrieveService/JoernScan',
                request_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.JoernScanRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.JoernScanResult.FromString,
                _registered_method=True)
        self.ListChunksByKind = channel.unary_unary(
                '/jervis.knowledgebase.KnowledgeRetrieveService/ListChunksByKind',
                request_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.ListByKindRequest.SerializeToString,
                response_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.ChunkList.FromString,
                _registered_method=True)


class KnowledgeRetrieveServiceServicer(object):
    """KnowledgeRetrieveService — vector + graph hybrid retrieval over the KB.
    Read-side RPCs only; ingestion lives in ingest.proto, graph walks live
    in graph.proto.
    """

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveSimple(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveHybrid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoernScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChunksByKind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeRetrieveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.RetrievalRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.EvidencePack.SerializeToString,
            ),
            'RetrieveSimple': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveSimple,
                    request_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.RetrievalRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.EvidencePack.SerializeToString,
            ),
            'RetrieveHybrid': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveHybrid,
                    request_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.HybridRetrievalRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.HybridEvidencePack.SerializeToString,
            ),
            'AnalyzeCode': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCode,
                    request_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.TraversalRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.JoernAnalyzeResult.SerializeToString,
            ),
            'JoernScan': grpc.unary_unary_rpc_method_handler(
                    servicer.JoernScan,
                    request_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.JoernScanRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.JoernScanResult.SerializeToString,
            ),
            'ListChunksByKind': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChunksByKind,
                    request_deserializer=jervis_dot_knowledgebase_dot_retrieve__pb2.ListByKindRequest.FromString,
                    response_serializer=jervis_dot_knowledgebase_dot_retrieve__pb2.ChunkList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.knowledgebase.KnowledgeRetrieveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.knowledgebase.KnowledgeRetrieveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeRetrieveService(object):
    """KnowledgeRetrieveService — vector + graph hybrid retrieval over the KB.
    Read-side RPCs only; ingestion lives in ingest.proto, graph walks live
    in graph.proto.
    """

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeRetrieveService/Retrieve',
            jervis_dot_knowledgebase_dot_retrieve__pb2.RetrievalRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_retrieve__pb2.EvidencePack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveSimple(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeRetrieveService/RetrieveSimple',
            jervis_dot_knowledgebase_dot_retrieve__pb2.RetrievalRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_retrieve__pb2.EvidencePack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveHybrid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeRetrieveService/RetrieveHybrid',
            jervis_dot_knowledgebase_dot_retrieve__pb2.HybridRetrievalRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_retrieve__pb2.HybridEvidencePack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeRetrieveService/AnalyzeCode',
            jervis_dot_knowledgebase_dot_retrieve__pb2.TraversalRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_retrieve__pb2.JoernAnalyzeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoernScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeRetrieveService/JoernScan',
            jervis_dot_knowledgebase_dot_retrieve__pb2.JoernScanRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_retrieve__pb2.JoernScanResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChunksByKind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.knowledgebase.KnowledgeRetrieveService/ListChunksByKind',
            jervis_dot_knowledgebase_dot_retrieve__pb2.ListByKindRequest.SerializeToString,
            jervis_dot_knowledgebase_dot_retrieve__pb2.ChunkList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
