package com.jervis.domain.background

enum class BackgroundTaskType {
    RAG_GAP_DISCOVERY,
    REPLY_SUGGESTIONS_PREP,
    RAG_SUMMARY_UPDATE,
    CODE_COMPLEXITY_SCAN,
    DOC_LINK_DISCOVERY,
    CODE_TO_DOC_LINKER,
    PLAN_BACKLOG_REFINEMENT,
    DAILY_BRIEFING_DRAFT,
    PENDING_TASK_ANALYSIS,
}
