package com.jervis.infrastructure.grpc

import com.jervis.contracts.interceptors.ServerContextInterceptor
import io.grpc.BindableService
import io.grpc.Server
import io.grpc.ServerInterceptors
import io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder
import io.grpc.protobuf.services.ProtoReflectionServiceV1
import jakarta.annotation.PostConstruct
import jakarta.annotation.PreDestroy
import mu.KotlinLogging
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Component
import java.util.concurrent.TimeUnit

// Single place the Kotlin server speaks gRPC. Every domain service impl
// that extends `BindableService` (e.g. `*GrpcImpl` classes generated by
// grpc-kotlin's CoroutineImplBase) is auto-discovered and registered
// behind the shared ServerContextInterceptor. Port 5501 is pod-to-pod
// only; Ktor :5500 keeps kRPC UI traffic unchanged.
@Component
class JervisGrpcServer(
    private val services: List<BindableService>,
    @Value("\${grpc.server.port:5501}")
    private val port: Int,
) {
    private val logger = KotlinLogging.logger {}
    private var server: Server? = null

    @PostConstruct
    fun start() {
        val interceptor = ServerContextInterceptor()
        val builder = NettyServerBuilder.forPort(port)

        for (svc in services) {
            builder.addService(ServerInterceptors.intercept(svc, interceptor))
            logger.info { "gRPC service registered: ${svc.bindService().serviceDescriptor.name}" }
        }
        builder.addService(ProtoReflectionServiceV1.newInstance())

        server = builder.build().also { it.start() }
        logger.info { "gRPC server listening on :$port (${services.size} services)" }
    }

    @PreDestroy
    fun stop() {
        runCatching {
            server?.shutdown()?.awaitTermination(5, TimeUnit.SECONDS)
            server?.shutdownNow()
        }
    }
}
