package com.jervis.configuration.prompts

enum class PromptTypeEnum {
    // PLANNING & ORCHESTRATION
    PLANNING_CREATE_PLAN,
    PLANNING_ANALYZE_QUESTION,
    TOOL_REASONING,
    CONTEXT_COMPACTION,
    FINALIZER_ANSWER,

    // INTERNAL/ANALYSIS PROMPTS
    CLIENT_DESCRIPTION_SHORT,
    CLIENT_DESCRIPTION_FULL,
    GIT_COMMIT_PROCESSING,
    CLASS_SUMMARY,

    // QUALIFIER PROMPTS (small model pre-filtering)
    EMAIL_QUALIFIER,
    JIRA_QUALIFIER,
    LINK_QUALIFIER,
    QUALIFIER,
}
