services:
  mongodb:
    image: mongo:latest
    container_name: jervis-mongodb-local
    ports:
      - "27017:27017"
    volumes:
      - mongodb_local_data:/data/db
    environment:
      # For local development without authentication
      - MONGO_INITDB_DATABASE=jervis
      # Uncomment the following lines if you want authentication
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - jervis-local

  qdrant:
    image: qdrant/qdrant:latest
    container_name: jervis-qdrant-local
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_local_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - jervis-local

volumes:
  mongodb_local_data:
  qdrant_local_storage:

networks:
  jervis-local:
    driver: bridge