# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/document_extraction/extract.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/document_extraction/extract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(jervis/document_extraction/extract.proto\x12\x1ajervis.document_extraction\x1a\x19jervis/common/types.proto\"\x84\x01\n\x0e\x45xtractRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x11\n\tmime_type\x18\x04 \x01(\t\x12\x10\n\x08max_tier\x18\x05 \x01(\t\"2\n\rExtractedPage\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"\xe7\x01\n\x0f\x45xtractResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12K\n\x08metadata\x18\x03 \x03(\x0b\x32\x39.jervis.document_extraction.ExtractResponse.MetadataEntry\x12\x38\n\x05pages\x18\x04 \x03(\x0b\x32).jervis.document_extraction.ExtractedPage\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\";\n\rHealthRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\"1\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t2\xe0\x01\n\x19\x44ocumentExtractionService\x12\x62\n\x07\x45xtract\x12*.jervis.document_extraction.ExtractRequest\x1a+.jervis.document_extraction.ExtractResponse\x12_\n\x06Health\x12).jervis.document_extraction.HealthRequest\x1a*.jervis.document_extraction.HealthResponseBE\n(com.jervis.contracts.document_extractionB\x17\x44ocumentExtractionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.document_extraction.extract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.jervis.contracts.document_extractionB\027DocumentExtractionProtoP\001'
  _globals['_EXTRACTRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_EXTRACTRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EXTRACTREQUEST']._serialized_start=100
  _globals['_EXTRACTREQUEST']._serialized_end=232
  _globals['_EXTRACTEDPAGE']._serialized_start=234
  _globals['_EXTRACTEDPAGE']._serialized_end=284
  _globals['_EXTRACTRESPONSE']._serialized_start=287
  _globals['_EXTRACTRESPONSE']._serialized_end=518
  _globals['_EXTRACTRESPONSE_METADATAENTRY']._serialized_start=471
  _globals['_EXTRACTRESPONSE_METADATAENTRY']._serialized_end=518
  _globals['_HEALTHREQUEST']._serialized_start=520
  _globals['_HEALTHREQUEST']._serialized_end=579
  _globals['_HEALTHRESPONSE']._serialized_start=581
  _globals['_HEALTHRESPONSE']._serialized_end=630
  _globals['_DOCUMENTEXTRACTIONSERVICE']._serialized_start=633
  _globals['_DOCUMENTEXTRACTIONSERVICE']._serialized_end=857
# @@protoc_insertion_point(module_scope)
