# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/server/agent_job_events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/server/agent_job_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$jervis/server/agent_job_events.proto\x12\rjervis.server\x1a\x19jervis/common/types.proto\"_\n\x1e\x41gentJobEventsSubscribeRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x11\n\tclient_id\x18\x02 \x01(\t\"\xcc\x02\n\x19\x41gentJobStateChangedEvent\x12\x14\n\x0c\x61gent_job_id\x18\x01 \x01(\t\x12\x0e\n\x06\x66lavor\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x11\n\tclient_id\x18\x05 \x01(\t\x12\x12\n\nproject_id\x18\x06 \x01(\t\x12\x13\n\x0bresource_id\x18\x07 \x01(\t\x12\x12\n\ngit_branch\x18\x08 \x01(\t\x12\x16\n\x0egit_commit_sha\x18\t \x01(\t\x12\x16\n\x0eresult_summary\x18\n \x01(\t\x12\x15\n\rerror_message\x18\x0b \x01(\t\x12\x11\n\tartifacts\x18\x0c \x03(\t\x12\x17\n\x0ftransitioned_at\x18\r \x01(\t\x12\x12\n\nstarted_at\x18\x0e \x01(\t\x12\x14\n\x0c\x63ompleted_at\x18\x0f \x01(\t2\x7f\n\x15\x41gentJobEventsService\x12\x66\n\tSubscribe\x12-.jervis.server.AgentJobEventsSubscribeRequest\x1a(.jervis.server.AgentJobStateChangedEvent0\x01\x42:\n\x1b\x63om.jervis.contracts.serverB\x19ServerAgentJobEventsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.server.agent_job_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.jervis.contracts.serverB\031ServerAgentJobEventsProtoP\001'
  _globals['_AGENTJOBEVENTSSUBSCRIBEREQUEST']._serialized_start=82
  _globals['_AGENTJOBEVENTSSUBSCRIBEREQUEST']._serialized_end=177
  _globals['_AGENTJOBSTATECHANGEDEVENT']._serialized_start=180
  _globals['_AGENTJOBSTATECHANGEDEVENT']._serialized_end=512
  _globals['_AGENTJOBEVENTSSERVICE']._serialized_start=514
  _globals['_AGENTJOBEVENTSSERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
