# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.server import cache_pb2 as jervis_dot_server_dot_cache__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/server/cache_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerCacheServiceStub(object):
    """ServerCacheService is the gRPC surface of the Kotlin server's in-memory
    cache invalidation. Called by the Python orchestrator after writing to
    a Mongo collection that has a Kotlin-side cache (today: `guidelines`).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invalidate = channel.unary_unary(
                '/jervis.server.ServerCacheService/Invalidate',
                request_serializer=jervis_dot_server_dot_cache__pb2.CacheInvalidateRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_cache__pb2.CacheInvalidateResponse.FromString,
                _registered_method=True)


class ServerCacheServiceServicer(object):
    """ServerCacheService is the gRPC surface of the Kotlin server's in-memory
    cache invalidation. Called by the Python orchestrator after writing to
    a Mongo collection that has a Kotlin-side cache (today: `guidelines`).
    """

    def Invalidate(self, request, context):
        """Drop the in-memory cache for `collection`. Unknown collection = no-op.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerCacheServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invalidate': grpc.unary_unary_rpc_method_handler(
                    servicer.Invalidate,
                    request_deserializer=jervis_dot_server_dot_cache__pb2.CacheInvalidateRequest.FromString,
                    response_serializer=jervis_dot_server_dot_cache__pb2.CacheInvalidateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.server.ServerCacheService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.server.ServerCacheService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerCacheService(object):
    """ServerCacheService is the gRPC surface of the Kotlin server's in-memory
    cache invalidation. Called by the Python orchestrator after writing to
    a Mongo collection that has a Kotlin-side cache (today: `guidelines`).
    """

    @staticmethod
    def Invalidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerCacheService/Invalidate',
            jervis_dot_server_dot_cache__pb2.CacheInvalidateRequest.SerializeToString,
            jervis_dot_server_dot_cache__pb2.CacheInvalidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
