# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/server/chat_approval.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/server/chat_approval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!jervis/server/chat_approval.proto\x12\rjervis.server\x1a\x19jervis/common/types.proto\"\xc5\x01\n\x18\x41pprovalBroadcastRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x13\n\x0b\x61pproval_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0c\n\x04tool\x18\x04 \x01(\t\x12\x0f\n\x07preview\x18\x05 \x01(\t\x12\x11\n\tclient_id\x18\x06 \x01(\t\x12\x12\n\nproject_id\x18\x07 \x01(\t\x12\x12\n\nsession_id\x18\x08 \x01(\t\"+\n\x19\x41pprovalBroadcastResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x8f\x01\n\x17\x41pprovalResolvedRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x13\n\x0b\x61pproval_id\x18\x02 \x01(\t\x12\x10\n\x08\x61pproved\x18\x03 \x01(\x08\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x11\n\tclient_id\x18\x05 \x01(\t\"*\n\x18\x41pprovalResolvedResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xd8\x01\n\x19ServerChatApprovalService\x12^\n\tBroadcast\x12\'.jervis.server.ApprovalBroadcastRequest\x1a(.jervis.server.ApprovalBroadcastResponse\x12[\n\x08Resolved\x12&.jervis.server.ApprovalResolvedRequest\x1a\'.jervis.server.ApprovalResolvedResponseB8\n\x1b\x63om.jervis.contracts.serverB\x17ServerChatApprovalProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.server.chat_approval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.jervis.contracts.serverB\027ServerChatApprovalProtoP\001'
  _globals['_APPROVALBROADCASTREQUEST']._serialized_start=80
  _globals['_APPROVALBROADCASTREQUEST']._serialized_end=277
  _globals['_APPROVALBROADCASTRESPONSE']._serialized_start=279
  _globals['_APPROVALBROADCASTRESPONSE']._serialized_end=322
  _globals['_APPROVALRESOLVEDREQUEST']._serialized_start=325
  _globals['_APPROVALRESOLVEDREQUEST']._serialized_end=468
  _globals['_APPROVALRESOLVEDRESPONSE']._serialized_start=470
  _globals['_APPROVALRESOLVEDRESPONSE']._serialized_end=512
  _globals['_SERVERCHATAPPROVALSERVICE']._serialized_start=515
  _globals['_SERVERCHATAPPROVALSERVICE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
