# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.server import chat_context_pb2 as jervis_dot_server_dot_chat__context__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/server/chat_context_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerChatContextServiceStub(object):
    """ServerChatContextService provides runtime context the Python chat
    handler injects into the LLM system prompt: clients+projects listing,
    pending user tasks summary, unclassified meetings count, user
    timezone. Read-only endpoints with small response payloads.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListClientsProjects = channel.unary_unary(
                '/jervis.server.ServerChatContextService/ListClientsProjects',
                request_serializer=jervis_dot_server_dot_chat__context__pb2.ClientsProjectsRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_chat__context__pb2.ClientsProjectsResponse.FromString,
                _registered_method=True)
        self.PendingUserTasksSummary = channel.unary_unary(
                '/jervis.server.ServerChatContextService/PendingUserTasksSummary',
                request_serializer=jervis_dot_server_dot_chat__context__pb2.PendingUserTasksRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_chat__context__pb2.PendingUserTasksResponse.FromString,
                _registered_method=True)
        self.UnclassifiedMeetingsCount = channel.unary_unary(
                '/jervis.server.ServerChatContextService/UnclassifiedMeetingsCount',
                request_serializer=jervis_dot_server_dot_chat__context__pb2.UnclassifiedCountRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_chat__context__pb2.UnclassifiedCountResponse.FromString,
                _registered_method=True)
        self.GetUserTimezone = channel.unary_unary(
                '/jervis.server.ServerChatContextService/GetUserTimezone',
                request_serializer=jervis_dot_server_dot_chat__context__pb2.UserTimezoneRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_chat__context__pb2.UserTimezoneResponse.FromString,
                _registered_method=True)
        self.GetActiveChatTopics = channel.unary_unary(
                '/jervis.server.ServerChatContextService/GetActiveChatTopics',
                request_serializer=jervis_dot_server_dot_chat__context__pb2.ActiveChatTopicsRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_chat__context__pb2.ActiveChatTopicsResponse.FromString,
                _registered_method=True)


class ServerChatContextServiceServicer(object):
    """ServerChatContextService provides runtime context the Python chat
    handler injects into the LLM system prompt: clients+projects listing,
    pending user tasks summary, unclassified meetings count, user
    timezone. Read-only endpoints with small response payloads.
    """

    def ListClientsProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PendingUserTasksSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnclassifiedMeetingsCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserTimezone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveChatTopics(self, request, context):
        """Active chat session topics — last-N messages of the active chat so the
        qualification agent knows what the user is currently working on.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerChatContextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListClientsProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListClientsProjects,
                    request_deserializer=jervis_dot_server_dot_chat__context__pb2.ClientsProjectsRequest.FromString,
                    response_serializer=jervis_dot_server_dot_chat__context__pb2.ClientsProjectsResponse.SerializeToString,
            ),
            'PendingUserTasksSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.PendingUserTasksSummary,
                    request_deserializer=jervis_dot_server_dot_chat__context__pb2.PendingUserTasksRequest.FromString,
                    response_serializer=jervis_dot_server_dot_chat__context__pb2.PendingUserTasksResponse.SerializeToString,
            ),
            'UnclassifiedMeetingsCount': grpc.unary_unary_rpc_method_handler(
                    servicer.UnclassifiedMeetingsCount,
                    request_deserializer=jervis_dot_server_dot_chat__context__pb2.UnclassifiedCountRequest.FromString,
                    response_serializer=jervis_dot_server_dot_chat__context__pb2.UnclassifiedCountResponse.SerializeToString,
            ),
            'GetUserTimezone': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserTimezone,
                    request_deserializer=jervis_dot_server_dot_chat__context__pb2.UserTimezoneRequest.FromString,
                    response_serializer=jervis_dot_server_dot_chat__context__pb2.UserTimezoneResponse.SerializeToString,
            ),
            'GetActiveChatTopics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveChatTopics,
                    request_deserializer=jervis_dot_server_dot_chat__context__pb2.ActiveChatTopicsRequest.FromString,
                    response_serializer=jervis_dot_server_dot_chat__context__pb2.ActiveChatTopicsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.server.ServerChatContextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.server.ServerChatContextService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerChatContextService(object):
    """ServerChatContextService provides runtime context the Python chat
    handler injects into the LLM system prompt: clients+projects listing,
    pending user tasks summary, unclassified meetings count, user
    timezone. Read-only endpoints with small response payloads.
    """

    @staticmethod
    def ListClientsProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerChatContextService/ListClientsProjects',
            jervis_dot_server_dot_chat__context__pb2.ClientsProjectsRequest.SerializeToString,
            jervis_dot_server_dot_chat__context__pb2.ClientsProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PendingUserTasksSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerChatContextService/PendingUserTasksSummary',
            jervis_dot_server_dot_chat__context__pb2.PendingUserTasksRequest.SerializeToString,
            jervis_dot_server_dot_chat__context__pb2.PendingUserTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnclassifiedMeetingsCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerChatContextService/UnclassifiedMeetingsCount',
            jervis_dot_server_dot_chat__context__pb2.UnclassifiedCountRequest.SerializeToString,
            jervis_dot_server_dot_chat__context__pb2.UnclassifiedCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserTimezone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerChatContextService/GetUserTimezone',
            jervis_dot_server_dot_chat__context__pb2.UserTimezoneRequest.SerializeToString,
            jervis_dot_server_dot_chat__context__pb2.UserTimezoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveChatTopics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerChatContextService/GetActiveChatTopics',
            jervis_dot_server_dot_chat__context__pb2.ActiveChatTopicsRequest.SerializeToString,
            jervis_dot_server_dot_chat__context__pb2.ActiveChatTopicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
