# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/server/connection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/server/connection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ejervis/server/connection.proto\x12\rjervis.server\x1a\x19jervis/common/types.proto\"Z\n\x15\x41pproveReloginRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x15\n\rconnection_id\x18\x02 \x01(\t\"a\n\x16\x41pproveReloginResponse\x12\x15\n\rconnection_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x12\n\npod_status\x18\x03 \x01(\x05\x12\r\n\x05\x65rror\x18\x04 \x01(\t2x\n\x17ServerConnectionService\x12]\n\x0e\x41pproveRelogin\x12$.jervis.server.ApproveReloginRequest\x1a%.jervis.server.ApproveReloginResponseB6\n\x1b\x63om.jervis.contracts.serverB\x15ServerConnectionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.server.connection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.jervis.contracts.serverB\025ServerConnectionProtoP\001'
  _globals['_APPROVERELOGINREQUEST']._serialized_start=76
  _globals['_APPROVERELOGINREQUEST']._serialized_end=166
  _globals['_APPROVERELOGINRESPONSE']._serialized_start=168
  _globals['_APPROVERELOGINRESPONSE']._serialized_end=265
  _globals['_SERVERCONNECTIONSERVICE']._serialized_start=267
  _globals['_SERVERCONNECTIONSERVICE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
