# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.server import connection_pb2 as jervis_dot_server_dot_connection__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/server/connection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerConnectionServiceStub(object):
    """Connection-lifecycle RPCs — currently just off-hours relogin approval.
    Kept as a standalone service because the domain is clearly "what does
    the server do on behalf of connections"; more lifecycle endpoints
    (health check, capabilities refresh, manual relogin trigger) land here
    as they migrate.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApproveRelogin = channel.unary_unary(
                '/jervis.server.ServerConnectionService/ApproveRelogin',
                request_serializer=jervis_dot_server_dot_connection__pb2.ApproveReloginRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_connection__pb2.ApproveReloginResponse.FromString,
                _registered_method=True)


class ServerConnectionServiceServicer(object):
    """Connection-lifecycle RPCs — currently just off-hours relogin approval.
    Kept as a standalone service because the domain is clearly "what does
    the server do on behalf of connections"; more lifecycle endpoints
    (health check, capabilities refresh, manual relogin trigger) land here
    as they migrate.
    """

    def ApproveRelogin(self, request, context):
        """Dispatch `approve_relogin` to the pod agent for the given connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerConnectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApproveRelogin': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveRelogin,
                    request_deserializer=jervis_dot_server_dot_connection__pb2.ApproveReloginRequest.FromString,
                    response_serializer=jervis_dot_server_dot_connection__pb2.ApproveReloginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.server.ServerConnectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.server.ServerConnectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerConnectionService(object):
    """Connection-lifecycle RPCs — currently just off-hours relogin approval.
    Kept as a standalone service because the domain is clearly "what does
    the server do on behalf of connections"; more lifecycle endpoints
    (health check, capabilities refresh, manual relogin trigger) land here
    as they migrate.
    """

    @staticmethod
    def ApproveRelogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerConnectionService/ApproveRelogin',
            jervis_dot_server_dot_connection__pb2.ApproveReloginRequest.SerializeToString,
            jervis_dot_server_dot_connection__pb2.ApproveReloginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
