# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.server import git_pb2 as jervis_dot_server_dot_git__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/server/git_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerGitServiceStub(object):
    """ServerGitService — git repository lifecycle (create via GitHub/GitLab
    API, clone into the project workspace). Also hosts GPG key lookup for
    agent commit signing (coding agent Jobs need the client's active key).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRepository = channel.unary_unary(
                '/jervis.server.ServerGitService/CreateRepository',
                request_serializer=jervis_dot_server_dot_git__pb2.CreateRepositoryRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_git__pb2.CreateRepositoryResponse.FromString,
                _registered_method=True)
        self.InitWorkspace = channel.unary_unary(
                '/jervis.server.ServerGitService/InitWorkspace',
                request_serializer=jervis_dot_server_dot_git__pb2.InitWorkspaceRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_git__pb2.InitWorkspaceResponse.FromString,
                _registered_method=True)
        self.GetWorkspaceStatus = channel.unary_unary(
                '/jervis.server.ServerGitService/GetWorkspaceStatus',
                request_serializer=jervis_dot_server_dot_git__pb2.WorkspaceStatusRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_git__pb2.WorkspaceStatusResponse.FromString,
                _registered_method=True)
        self.GetGpgKey = channel.unary_unary(
                '/jervis.server.ServerGitService/GetGpgKey',
                request_serializer=jervis_dot_server_dot_git__pb2.GetGpgKeyRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_git__pb2.GetGpgKeyResponse.FromString,
                _registered_method=True)


class ServerGitServiceServicer(object):
    """ServerGitService — git repository lifecycle (create via GitHub/GitLab
    API, clone into the project workspace). Also hosts GPG key lookup for
    agent commit signing (coding agent Jobs need the client's active key).
    """

    def CreateRepository(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspaceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGpgKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerGitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRepository': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRepository,
                    request_deserializer=jervis_dot_server_dot_git__pb2.CreateRepositoryRequest.FromString,
                    response_serializer=jervis_dot_server_dot_git__pb2.CreateRepositoryResponse.SerializeToString,
            ),
            'InitWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.InitWorkspace,
                    request_deserializer=jervis_dot_server_dot_git__pb2.InitWorkspaceRequest.FromString,
                    response_serializer=jervis_dot_server_dot_git__pb2.InitWorkspaceResponse.SerializeToString,
            ),
            'GetWorkspaceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspaceStatus,
                    request_deserializer=jervis_dot_server_dot_git__pb2.WorkspaceStatusRequest.FromString,
                    response_serializer=jervis_dot_server_dot_git__pb2.WorkspaceStatusResponse.SerializeToString,
            ),
            'GetGpgKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGpgKey,
                    request_deserializer=jervis_dot_server_dot_git__pb2.GetGpgKeyRequest.FromString,
                    response_serializer=jervis_dot_server_dot_git__pb2.GetGpgKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.server.ServerGitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.server.ServerGitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerGitService(object):
    """ServerGitService — git repository lifecycle (create via GitHub/GitLab
    API, clone into the project workspace). Also hosts GPG key lookup for
    agent commit signing (coding agent Jobs need the client's active key).
    """

    @staticmethod
    def CreateRepository(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerGitService/CreateRepository',
            jervis_dot_server_dot_git__pb2.CreateRepositoryRequest.SerializeToString,
            jervis_dot_server_dot_git__pb2.CreateRepositoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerGitService/InitWorkspace',
            jervis_dot_server_dot_git__pb2.InitWorkspaceRequest.SerializeToString,
            jervis_dot_server_dot_git__pb2.InitWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkspaceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerGitService/GetWorkspaceStatus',
            jervis_dot_server_dot_git__pb2.WorkspaceStatusRequest.SerializeToString,
            jervis_dot_server_dot_git__pb2.WorkspaceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGpgKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerGitService/GetGpgKey',
            jervis_dot_server_dot_git__pb2.GetGpgKeyRequest.SerializeToString,
            jervis_dot_server_dot_git__pb2.GetGpgKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
