# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.server import gpu_idle_pb2 as jervis_dot_server_dot_gpu__idle__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/server/gpu_idle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerGpuIdleServiceStub(object):
    """ServerGpuIdleService is a reverse callback surface: the ollama-router
    calls the Kotlin server when the local GPU pool has been idle for
    longer than `gpu_idle_notify_after_s` (default 2 min). The server
    triggers BackgroundEngine.onGpuIdle() so analytical / proactive tasks
    run immediately instead of waiting for the 30-min idle review loop.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GpuIdle = channel.unary_unary(
                '/jervis.server.ServerGpuIdleService/GpuIdle',
                request_serializer=jervis_dot_server_dot_gpu__idle__pb2.GpuIdleRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_gpu__idle__pb2.GpuIdleResponse.FromString,
                _registered_method=True)


class ServerGpuIdleServiceServicer(object):
    """ServerGpuIdleService is a reverse callback surface: the ollama-router
    calls the Kotlin server when the local GPU pool has been idle for
    longer than `gpu_idle_notify_after_s` (default 2 min). The server
    triggers BackgroundEngine.onGpuIdle() so analytical / proactive tasks
    run immediately instead of waiting for the 30-min idle review loop.
    """

    def GpuIdle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerGpuIdleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GpuIdle': grpc.unary_unary_rpc_method_handler(
                    servicer.GpuIdle,
                    request_deserializer=jervis_dot_server_dot_gpu__idle__pb2.GpuIdleRequest.FromString,
                    response_serializer=jervis_dot_server_dot_gpu__idle__pb2.GpuIdleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.server.ServerGpuIdleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.server.ServerGpuIdleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerGpuIdleService(object):
    """ServerGpuIdleService is a reverse callback surface: the ollama-router
    calls the Kotlin server when the local GPU pool has been idle for
    longer than `gpu_idle_notify_after_s` (default 2 min). The server
    triggers BackgroundEngine.onGpuIdle() so analytical / proactive tasks
    run immediately instead of waiting for the 30-min idle review loop.
    """

    @staticmethod
    def GpuIdle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerGpuIdleService/GpuIdle',
            jervis_dot_server_dot_gpu__idle__pb2.GpuIdleRequest.SerializeToString,
            jervis_dot_server_dot_gpu__idle__pb2.GpuIdleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
