# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.server import meeting_alone_pb2 as jervis_dot_server_dot_meeting__alone__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/server/meeting_alone_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerMeetingAloneServiceStub(object):
    """ServerMeetingAloneService — "alone in meeting" chat bubble resolution
    (product §10a). Called by the MCP tool layer when the user answers an
    alone-check push with "Odejít" (Leave) or "Zůstat" (Stay).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Leave = channel.unary_unary(
                '/jervis.server.ServerMeetingAloneService/Leave',
                request_serializer=jervis_dot_server_dot_meeting__alone__pb2.LeaveRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_meeting__alone__pb2.LeaveResponse.FromString,
                _registered_method=True)
        self.Stay = channel.unary_unary(
                '/jervis.server.ServerMeetingAloneService/Stay',
                request_serializer=jervis_dot_server_dot_meeting__alone__pb2.StayRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_meeting__alone__pb2.StayResponse.FromString,
                _registered_method=True)


class ServerMeetingAloneServiceServicer(object):
    """ServerMeetingAloneService — "alone in meeting" chat bubble resolution
    (product §10a). Called by the MCP tool layer when the user answers an
    alone-check push with "Odejít" (Leave) or "Zůstat" (Stay).
    """

    def Leave(self, request, context):
        """Dispatch `leave_meeting` to the pod agent; stops recording +
        clicks Leave in Teams + reports presence=false.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stay(self, request, context):
        """Suppress further alone-check pushes for `suppress_minutes`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerMeetingAloneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Leave': grpc.unary_unary_rpc_method_handler(
                    servicer.Leave,
                    request_deserializer=jervis_dot_server_dot_meeting__alone__pb2.LeaveRequest.FromString,
                    response_serializer=jervis_dot_server_dot_meeting__alone__pb2.LeaveResponse.SerializeToString,
            ),
            'Stay': grpc.unary_unary_rpc_method_handler(
                    servicer.Stay,
                    request_deserializer=jervis_dot_server_dot_meeting__alone__pb2.StayRequest.FromString,
                    response_serializer=jervis_dot_server_dot_meeting__alone__pb2.StayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.server.ServerMeetingAloneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.server.ServerMeetingAloneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerMeetingAloneService(object):
    """ServerMeetingAloneService — "alone in meeting" chat bubble resolution
    (product §10a). Called by the MCP tool layer when the user answers an
    alone-check push with "Odejít" (Leave) or "Zůstat" (Stay).
    """

    @staticmethod
    def Leave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerMeetingAloneService/Leave',
            jervis_dot_server_dot_meeting__alone__pb2.LeaveRequest.SerializeToString,
            jervis_dot_server_dot_meeting__alone__pb2.LeaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerMeetingAloneService/Stay',
            jervis_dot_server_dot_meeting__alone__pb2.StayRequest.SerializeToString,
            jervis_dot_server_dot_meeting__alone__pb2.StayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
