# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/server/meeting_helper_callbacks.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/server/meeting_helper_callbacks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,jervis/server/meeting_helper_callbacks.proto\x12\rjervis.server\x1a\x19jervis/common/types.proto\"\xb7\x01\n\x11HelperPushRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x12\n\nmeeting_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x05 \x01(\t\x12\x11\n\tfrom_lang\x18\x06 \x01(\t\x12\x0f\n\x07to_lang\x18\x07 \x01(\t\x12\x11\n\ttimestamp\x18\x08 \x01(\t\".\n\rHelperPushAck\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2t\n#ServerMeetingHelperCallbacksService\x12M\n\x0bPushMessage\x12 .jervis.server.HelperPushRequest\x1a\x1c.jervis.server.HelperPushAckBB\n\x1b\x63om.jervis.contracts.serverB!ServerMeetingHelperCallbacksProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.server.meeting_helper_callbacks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.jervis.contracts.serverB!ServerMeetingHelperCallbacksProtoP\001'
  _globals['_HELPERPUSHREQUEST']._serialized_start=91
  _globals['_HELPERPUSHREQUEST']._serialized_end=274
  _globals['_HELPERPUSHACK']._serialized_start=276
  _globals['_HELPERPUSHACK']._serialized_end=322
  _globals['_SERVERMEETINGHELPERCALLBACKSSERVICE']._serialized_start=324
  _globals['_SERVERMEETINGHELPERCALLBACKSSERVICE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
