# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/server/o365_resources.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/server/o365_resources.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"jervis/server/o365_resources.proto\x12\rjervis.server\x1a\x19jervis/common/types.proto\"q\n\x15ListDiscoveredRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x15\n\rconnection_id\x18\x02 \x01(\t\x12\x15\n\rresource_type\x18\x03 \x01(\t\"N\n\x16ListDiscoveredResponse\x12\x34\n\tresources\x18\x01 \x03(\x0b\x32!.jervis.server.DiscoveredResource\"\xc7\x01\n\x12\x44iscoveredResource\x12\x13\n\x0b\x65xternal_id\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x11\n\tteam_name\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x08\x12\x1b\n\x13\x64iscovered_at_epoch\x18\x07 \x01(\x03\x12\x1a\n\x12last_seen_at_epoch\x18\x08 \x01(\x03\"T\n\x13LastActivityRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x11\n\tclient_id\x18\x02 \x01(\t\"3\n\x14LastActivityResponse\x12\x1b\n\x13last_active_seconds\x18\x01 \x01(\x03\x32\x85\x01\n$ServerO365DiscoveredResourcesService\x12]\n\x0eListDiscovered\x12$.jervis.server.ListDiscoveredRequest\x1a%.jervis.server.ListDiscoveredResponse2t\n\x19ServerUserActivityService\x12W\n\x0cLastActivity\x12\".jervis.server.LastActivityRequest\x1a#.jervis.server.LastActivityResponseB9\n\x1b\x63om.jervis.contracts.serverB\x18ServerO365ResourcesProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.server.o365_resources_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.jervis.contracts.serverB\030ServerO365ResourcesProtoP\001'
  _globals['_LISTDISCOVEREDREQUEST']._serialized_start=80
  _globals['_LISTDISCOVEREDREQUEST']._serialized_end=193
  _globals['_LISTDISCOVEREDRESPONSE']._serialized_start=195
  _globals['_LISTDISCOVEREDRESPONSE']._serialized_end=273
  _globals['_DISCOVEREDRESOURCE']._serialized_start=276
  _globals['_DISCOVEREDRESOURCE']._serialized_end=475
  _globals['_LASTACTIVITYREQUEST']._serialized_start=477
  _globals['_LASTACTIVITYREQUEST']._serialized_end=561
  _globals['_LASTACTIVITYRESPONSE']._serialized_start=563
  _globals['_LASTACTIVITYRESPONSE']._serialized_end=614
  _globals['_SERVERO365DISCOVEREDRESOURCESSERVICE']._serialized_start=617
  _globals['_SERVERO365DISCOVEREDRESOURCESSERVICE']._serialized_end=750
  _globals['_SERVERUSERACTIVITYSERVICE']._serialized_start=752
  _globals['_SERVERUSERACTIVITYSERVICE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
