# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/server/openrouter_settings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/server/openrouter_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'jervis/server/openrouter_settings.proto\x12\rjervis.server\x1a\x19jervis/common/types.proto\"J\n\x1cGetOpenRouterSettingsRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\"2\n\x1dGetOpenRouterSettingsResponse\x12\x11\n\tbody_json\x18\x01 \x01(\t\"Z\n\x18PersistModelStatsRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x12\n\nstats_json\x18\x02 \x01(\t\"7\n\x19PersistModelStatsResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06models\x18\x02 \x01(\x05\x32\xf3\x01\n\x1fServerOpenRouterSettingsService\x12h\n\x0bGetSettings\x12+.jervis.server.GetOpenRouterSettingsRequest\x1a,.jervis.server.GetOpenRouterSettingsResponse\x12\x66\n\x11PersistModelStats\x12\'.jervis.server.PersistModelStatsRequest\x1a(.jervis.server.PersistModelStatsResponseB>\n\x1b\x63om.jervis.contracts.serverB\x1dServerOpenRouterSettingsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.server.openrouter_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.jervis.contracts.serverB\035ServerOpenRouterSettingsProtoP\001'
  _globals['_GETOPENROUTERSETTINGSREQUEST']._serialized_start=85
  _globals['_GETOPENROUTERSETTINGSREQUEST']._serialized_end=159
  _globals['_GETOPENROUTERSETTINGSRESPONSE']._serialized_start=161
  _globals['_GETOPENROUTERSETTINGSRESPONSE']._serialized_end=211
  _globals['_PERSISTMODELSTATSREQUEST']._serialized_start=213
  _globals['_PERSISTMODELSTATSREQUEST']._serialized_end=303
  _globals['_PERSISTMODELSTATSRESPONSE']._serialized_start=305
  _globals['_PERSISTMODELSTATSRESPONSE']._serialized_end=360
  _globals['_SERVEROPENROUTERSETTINGSSERVICE']._serialized_start=363
  _globals['_SERVEROPENROUTERSETTINGSSERVICE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
