# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.server import orchestrator_progress_pb2 as jervis_dot_server_dot_orchestrator__progress__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/server/orchestrator_progress_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerOrchestratorProgressServiceStub(object):
    """ServerOrchestratorProgressService is the reverse-callback surface the
    Python orchestrator (and the correction agent) use to push progress,
    status and graph updates into the Kotlin server. All calls are
    fire-and-forget from Python's perspective — the server acks with
    `ok=true` and dispatches async fan-out to NotificationRpc / chat streams.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OrchestratorProgress = channel.unary_unary(
                '/jervis.server.ServerOrchestratorProgressService/OrchestratorProgress',
                request_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.OrchestratorProgressRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
                _registered_method=True)
        self.OrchestratorStatus = channel.unary_unary(
                '/jervis.server.ServerOrchestratorProgressService/OrchestratorStatus',
                request_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.OrchestratorStatusRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
                _registered_method=True)
        self.QualificationDone = channel.unary_unary(
                '/jervis.server.ServerOrchestratorProgressService/QualificationDone',
                request_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.QualificationDoneRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
                _registered_method=True)
        self.MemoryGraphChanged = channel.unary_unary(
                '/jervis.server.ServerOrchestratorProgressService/MemoryGraphChanged',
                request_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.MemoryGraphChangedRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
                _registered_method=True)
        self.ThinkingGraphUpdate = channel.unary_unary(
                '/jervis.server.ServerOrchestratorProgressService/ThinkingGraphUpdate',
                request_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.ThinkingGraphUpdateRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
                _registered_method=True)
        self.CorrectionProgress = channel.unary_unary(
                '/jervis.server.ServerOrchestratorProgressService/CorrectionProgress',
                request_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.CorrectionProgressRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
                _registered_method=True)


class ServerOrchestratorProgressServiceServicer(object):
    """ServerOrchestratorProgressService is the reverse-callback surface the
    Python orchestrator (and the correction agent) use to push progress,
    status and graph updates into the Kotlin server. All calls are
    fire-and-forget from Python's perspective — the server acks with
    `ok=true` and dispatches async fan-out to NotificationRpc / chat streams.
    """

    def OrchestratorProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrchestratorStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QualificationDone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryGraphChanged(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ThinkingGraphUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CorrectionProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerOrchestratorProgressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OrchestratorProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.OrchestratorProgress,
                    request_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.OrchestratorProgressRequest.FromString,
                    response_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.SerializeToString,
            ),
            'OrchestratorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.OrchestratorStatus,
                    request_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.OrchestratorStatusRequest.FromString,
                    response_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.SerializeToString,
            ),
            'QualificationDone': grpc.unary_unary_rpc_method_handler(
                    servicer.QualificationDone,
                    request_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.QualificationDoneRequest.FromString,
                    response_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.SerializeToString,
            ),
            'MemoryGraphChanged': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryGraphChanged,
                    request_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.MemoryGraphChangedRequest.FromString,
                    response_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.SerializeToString,
            ),
            'ThinkingGraphUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.ThinkingGraphUpdate,
                    request_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.ThinkingGraphUpdateRequest.FromString,
                    response_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.SerializeToString,
            ),
            'CorrectionProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.CorrectionProgress,
                    request_deserializer=jervis_dot_server_dot_orchestrator__progress__pb2.CorrectionProgressRequest.FromString,
                    response_serializer=jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.server.ServerOrchestratorProgressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.server.ServerOrchestratorProgressService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerOrchestratorProgressService(object):
    """ServerOrchestratorProgressService is the reverse-callback surface the
    Python orchestrator (and the correction agent) use to push progress,
    status and graph updates into the Kotlin server. All calls are
    fire-and-forget from Python's perspective — the server acks with
    `ok=true` and dispatches async fan-out to NotificationRpc / chat streams.
    """

    @staticmethod
    def OrchestratorProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerOrchestratorProgressService/OrchestratorProgress',
            jervis_dot_server_dot_orchestrator__progress__pb2.OrchestratorProgressRequest.SerializeToString,
            jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrchestratorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerOrchestratorProgressService/OrchestratorStatus',
            jervis_dot_server_dot_orchestrator__progress__pb2.OrchestratorStatusRequest.SerializeToString,
            jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QualificationDone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerOrchestratorProgressService/QualificationDone',
            jervis_dot_server_dot_orchestrator__progress__pb2.QualificationDoneRequest.SerializeToString,
            jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryGraphChanged(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerOrchestratorProgressService/MemoryGraphChanged',
            jervis_dot_server_dot_orchestrator__progress__pb2.MemoryGraphChangedRequest.SerializeToString,
            jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ThinkingGraphUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerOrchestratorProgressService/ThinkingGraphUpdate',
            jervis_dot_server_dot_orchestrator__progress__pb2.ThinkingGraphUpdateRequest.SerializeToString,
            jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CorrectionProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerOrchestratorProgressService/CorrectionProgress',
            jervis_dot_server_dot_orchestrator__progress__pb2.CorrectionProgressRequest.SerializeToString,
            jervis_dot_server_dot_orchestrator__progress__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
