# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.server import proactive_pb2 as jervis_dot_server_dot_proactive__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/server/proactive_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServerProactiveServiceStub(object):
    """ServerProactiveService exposes scheduled proactive triggers — morning
    briefing / overdue invoice check / weekly summary / VIP email alert.
    Invoked by the Python orchestrator's scheduler; each RPC returns a
    small typed result that callers log.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MorningBriefing = channel.unary_unary(
                '/jervis.server.ServerProactiveService/MorningBriefing',
                request_serializer=jervis_dot_server_dot_proactive__pb2.MorningBriefingRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_proactive__pb2.MorningBriefingResponse.FromString,
                _registered_method=True)
        self.OverdueCheck = channel.unary_unary(
                '/jervis.server.ServerProactiveService/OverdueCheck',
                request_serializer=jervis_dot_server_dot_proactive__pb2.OverdueCheckRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_proactive__pb2.OverdueCheckResponse.FromString,
                _registered_method=True)
        self.WeeklySummary = channel.unary_unary(
                '/jervis.server.ServerProactiveService/WeeklySummary',
                request_serializer=jervis_dot_server_dot_proactive__pb2.WeeklySummaryRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_proactive__pb2.WeeklySummaryResponse.FromString,
                _registered_method=True)
        self.VipAlert = channel.unary_unary(
                '/jervis.server.ServerProactiveService/VipAlert',
                request_serializer=jervis_dot_server_dot_proactive__pb2.VipAlertRequest.SerializeToString,
                response_deserializer=jervis_dot_server_dot_proactive__pb2.VipAlertResponse.FromString,
                _registered_method=True)


class ServerProactiveServiceServicer(object):
    """ServerProactiveService exposes scheduled proactive triggers — morning
    briefing / overdue invoice check / weekly summary / VIP email alert.
    Invoked by the Python orchestrator's scheduler; each RPC returns a
    small typed result that callers log.
    """

    def MorningBriefing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OverdueCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WeeklySummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VipAlert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerProactiveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MorningBriefing': grpc.unary_unary_rpc_method_handler(
                    servicer.MorningBriefing,
                    request_deserializer=jervis_dot_server_dot_proactive__pb2.MorningBriefingRequest.FromString,
                    response_serializer=jervis_dot_server_dot_proactive__pb2.MorningBriefingResponse.SerializeToString,
            ),
            'OverdueCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.OverdueCheck,
                    request_deserializer=jervis_dot_server_dot_proactive__pb2.OverdueCheckRequest.FromString,
                    response_serializer=jervis_dot_server_dot_proactive__pb2.OverdueCheckResponse.SerializeToString,
            ),
            'WeeklySummary': grpc.unary_unary_rpc_method_handler(
                    servicer.WeeklySummary,
                    request_deserializer=jervis_dot_server_dot_proactive__pb2.WeeklySummaryRequest.FromString,
                    response_serializer=jervis_dot_server_dot_proactive__pb2.WeeklySummaryResponse.SerializeToString,
            ),
            'VipAlert': grpc.unary_unary_rpc_method_handler(
                    servicer.VipAlert,
                    request_deserializer=jervis_dot_server_dot_proactive__pb2.VipAlertRequest.FromString,
                    response_serializer=jervis_dot_server_dot_proactive__pb2.VipAlertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.server.ServerProactiveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.server.ServerProactiveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerProactiveService(object):
    """ServerProactiveService exposes scheduled proactive triggers — morning
    briefing / overdue invoice check / weekly summary / VIP email alert.
    Invoked by the Python orchestrator's scheduler; each RPC returns a
    small typed result that callers log.
    """

    @staticmethod
    def MorningBriefing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerProactiveService/MorningBriefing',
            jervis_dot_server_dot_proactive__pb2.MorningBriefingRequest.SerializeToString,
            jervis_dot_server_dot_proactive__pb2.MorningBriefingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OverdueCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerProactiveService/OverdueCheck',
            jervis_dot_server_dot_proactive__pb2.OverdueCheckRequest.SerializeToString,
            jervis_dot_server_dot_proactive__pb2.OverdueCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WeeklySummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerProactiveService/WeeklySummary',
            jervis_dot_server_dot_proactive__pb2.WeeklySummaryRequest.SerializeToString,
            jervis_dot_server_dot_proactive__pb2.WeeklySummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VipAlert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.server.ServerProactiveService/VipAlert',
            jervis_dot_server_dot_proactive__pb2.VipAlertRequest.SerializeToString,
            jervis_dot_server_dot_proactive__pb2.VipAlertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
