# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/server/whatsapp_session.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/server/whatsapp_session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$jervis/server/whatsapp_session.proto\x12\rjervis.server\x1a\x19jervis/common/types.proto\"\x93\x01\n\x1bWhatsappSessionEventRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x15\n\rconnection_id\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x0f\n\x07vnc_url\x18\x05 \x01(\t\"*\n\x1cWhatsappSessionEventResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\xa7\x01\n\x1bWhatsappCapabilitiesRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x15\n\rconnection_id\x18\x03 \x01(\t\x12\x1e\n\x16\x61vailable_capabilities\x18\x04 \x03(\t\x12\x12\n\nchat_count\x18\x05 \x01(\x05\"*\n\x1cWhatsappCapabilitiesResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xfa\x01\n\x1cServerWhatsappSessionService\x12g\n\x0cSessionEvent\x12*.jervis.server.WhatsappSessionEventRequest\x1a+.jervis.server.WhatsappSessionEventResponse\x12q\n\x16\x43\x61pabilitiesDiscovered\x12*.jervis.server.WhatsappCapabilitiesRequest\x1a+.jervis.server.WhatsappCapabilitiesResponseB;\n\x1b\x63om.jervis.contracts.serverB\x1aServerWhatsappSessionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.server.whatsapp_session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.jervis.contracts.serverB\032ServerWhatsappSessionProtoP\001'
  _globals['_WHATSAPPSESSIONEVENTREQUEST']._serialized_start=83
  _globals['_WHATSAPPSESSIONEVENTREQUEST']._serialized_end=230
  _globals['_WHATSAPPSESSIONEVENTRESPONSE']._serialized_start=232
  _globals['_WHATSAPPSESSIONEVENTRESPONSE']._serialized_end=274
  _globals['_WHATSAPPCAPABILITIESREQUEST']._serialized_start=277
  _globals['_WHATSAPPCAPABILITIESREQUEST']._serialized_end=444
  _globals['_WHATSAPPCAPABILITIESRESPONSE']._serialized_start=446
  _globals['_WHATSAPPCAPABILITIESRESPONSE']._serialized_end=488
  _globals['_SERVERWHATSAPPSESSIONSERVICE']._serialized_start=491
  _globals['_SERVERWHATSAPPSESSIONSERVICE']._serialized_end=741
# @@protoc_insertion_point(module_scope)
