package com.jervis.configuration.prompts

enum class ToolTypeEnum {
    // KNOWLEDGE MANAGEMENT
    KNOWLEDGE_SEARCH_TOOL,
    KNOWLEDGE_STORE_TOOL,
    SOURCE_FETCH_ORIGINAL_TOOL,

    // DOCUMENT PROCESSING
    DOCUMENT_EXTRACT_TEXT_TOOL,
    DOCUMENT_FROM_WEB_TOOL,

    // CODE ANALYSIS & MODIFICATION
    CODE_MODIFY_TOOL,
    CODE_ANALYZE_TOOL,

    // PROJECT MANAGEMENT
    PROJECT_EXPLORE_STRUCTURE_TOOL,
    PROJECT_GIT_SYNC_TOOL,

    // SYSTEM OPERATIONS
    SYSTEM_EXECUTE_COMMAND_TOOL,
    SYSTEM_SCHEDULE_TASK_TOOL,
    SYSTEM_MANAGE_LINK_SAFETY_TOOL,
    SYSTEM_INDEX_LINK_TOOL,
    SYSTEM_QUALIFIER_RULES_MANAGE_TOOL,
    CREATE_PENDING_TASK_TOOL,
    CONSOLIDATE_STEPS_TOOL,

    // USER TASK MANAGEMENT
    TASK_CREATE_USER_TASK_TOOL,
    TASK_QUERY_USER_TASKS_TOOL,

    // USER REQUIREMENT MANAGEMENT
    REQUIREMENT_CREATE_USER_TOOL,
    REQUIREMENT_QUERY_USER_TOOL,
    REQUIREMENT_UPDATE_USER_TOOL,

    // COMMUNICATION
    COMMUNICATION_EMAIL_TOOL,
    COMMUNICATION_TEAMS_TOOL,
    COMMUNICATION_SLACK_TOOL,
    COMMUNICATION_USER_DIALOG_TOOL,

    // CONTENT PROCESSING
    CONTENT_SEARCH_WEB_TOOL,
}
