package com.jervis.dto.git

import kotlinx.serialization.Serializable

/**
 * Placeholders available for Git commit message patterns.
 * These are replaced by the server when creating commits.
 *
 * Example pattern: "[$project] $message ($task_number)"
 * Resolved to: "[nUFO] Add user authentication (UFO-123)"
 */
@Serializable
enum class GitCommitPlaceholder(
    val placeholder: String,
    val description: String,
    val example: String,
) {
    /**
     * Task number from bug tracker (e.g., Jira issue key).
     * Empty if no bug tracker task associated.
     */
    TASK_NUMBER(
        placeholder = "\$task_number",
        description = "Číslo úlohy z bug trackeru",
        example = "UFO-123",
    ),

    /**
     * Internal Jervis task ID (ObjectId).
     */
    TASK_ID(
        placeholder = "\$task_id",
        description = "Interní ID úlohy v Jervis",
        example = "65f1a2b3c4d5e6f7a8b9c0d1",
    ),

    /**
     * Task title/summary.
     */
    TASK_TITLE(
        placeholder = "\$task_title",
        description = "Název úlohy",
        example = "Implementovat autentizaci",
    ),

    /**
     * Task type enum name.
     */
    TASK_TYPE(
        placeholder = "\$task_type",
        description = "Typ úlohy",
        example = "USER_INPUT_PROCESSING",
    ),

    /**
     * Project name.
     */
    PROJECT(
        placeholder = "\$project",
        description = "Název projektu",
        example = "nUFO",
    ),

    /**
     * Client name.
     */
    CLIENT(
        placeholder = "\$client",
        description = "Název klienta",
        example = "BMS Systems",
    ),

    /**
     * Current git branch name.
     */
    BRANCH(
        placeholder = "\$branch",
        description = "Název větve",
        example = "feature/auth",
    ),

    /**
     * Main commit message (generated by agent or user).
     * This is the core content of the commit.
     */
    MESSAGE(
        placeholder = "\$message",
        description = "Hlavní zpráva commitu (generovaná)",
        example = "Add user authentication endpoints",
    ),

    /**
     * Detailed description of changes (optional).
     */
    DETAIL(
        placeholder = "\$detail",
        description = "Detailní popis změn",
        example = "- Added login/logout endpoints\n- Implemented JWT token validation",
    ),

    /**
     * Author name (from git config).
     */
    AUTHOR(
        placeholder = "\$author",
        description = "Jméno autora",
        example = "Jervis Agent",
    ),

    /**
     * Current date (YYYY-MM-DD).
     */
    DATE(
        placeholder = "\$date",
        description = "Datum (YYYY-MM-DD)",
        example = "2026-02-13",
    ),

    /**
     * Current time (HH:MM:SS).
     */
    TIME(
        placeholder = "\$time",
        description = "Čas (HH:MM:SS)",
        example = "21:45:30",
    ),

    /**
     * ISO-8601 timestamp.
     */
    TIMESTAMP(
        placeholder = "\$timestamp",
        description = "Časové razítko (ISO-8601)",
        example = "2026-02-13T21:45:30Z",
    ),
    ;

    companion object {
        /**
         * Get all placeholders for UI display (e.g., helper text).
         */
        fun getAllPlaceholders(): List<String> = entries.map { it.placeholder }

        /**
         * Get placeholder description for tooltip/help.
         */
        fun getDescriptions(): Map<String, String> = entries.associate { it.placeholder to it.description }

        /**
         * Default pattern if none specified.
         */
        const val DEFAULT_PATTERN = "\$message"

        /**
         * Common pattern examples for UI suggestions.
         */
        val COMMON_PATTERNS = listOf(
            "\$message",
            "[\$project] \$message",
            "\$task_number: \$message",
            "[\$task_number] \$message",
            "\$project: \$message (\$task_number)",
        )
    }
}
