package com.jervis.configuration.prompts

enum class McpToolType {
    RAG_QUERY,
    JOERN,
    TERMINAL,
    LLM,
    USER_INTERACTION,
    CODE_WRITE,
    SCOPE_RESOLUTION,
    PLANNER,
    CODE_EXTRACTOR,
    TASK_SCHEDULER,
    TASK_VIEWER,
    GIT,
    EMAIL,
    TEAMS,
    SLACK,
    REINDEX,
    AGENT_TOOL_SUFFIX,
    FINALIZER,
    TRANSLATION,
    CLASS_SUMMARY,
    DEPENDENCY_ANALYSIS,
}
