package com.jervis.configuration.prompts

enum class PromptTypeEnum {
    // KNOWLEDGE MANAGEMENT
    KNOWLEDGE_SEARCH,
    KNOWLEDGE_STORE,
    RAG_RESULTS_SYNTHESIS,

    // DOCUMENT PROCESSING
    DOCUMENT_EXTRACT_TEXT,
    DOCUMENT_FROM_WEB,

    // CODE ANALYSIS & MODIFICATION
    CODE_MODIFY,
    CODE_ANALYZE,

    // PROJECT MANAGEMENT
    PROJECT_EXPLORE_STRUCTURE,
    PROJECT_REFRESH_INDEX,
    PROJECT_VERSION_CONTROL,

    // SYSTEM OPERATIONS
    SYSTEM_EXECUTE_COMMAND,
    SYSTEM_SCHEDULE_TASK,
    SYSTEM_VIEW_TASKS,

    // COMMUNICATION
    COMMUNICATION_EMAIL,
    COMMUNICATION_TEAMS,
    COMMUNICATION_SLACK,
    COMMUNICATION_USER_DIALOG,

    // ANALYSIS & REASONING
    ANALYSIS_REASONING,
    TASK_RESOLUTION_CHECKER,

    // CONTENT PROCESSING
    CONTENT_SEARCH_WEB,
    CONTENT_SPLIT_SENTENCES,

    // PLANNING & ORCHESTRATION
    PLANNING_CREATE_PLAN,
    PLANNING_CREATE_GOALS,
    PLANNING_ANALYZE_QUESTION,
    PLANNING_RAG_QUERY_EXPAND,
    FINALIZER_ANSWER,

    // INTERNAL/ANALYSIS PROMPTS (unchanged)
    CLIENT_DESCRIPTION_SHORT,
    CLIENT_DESCRIPTION_FULL,
    COMPREHENSIVE_FILE_ANALYSIS,
    MEETING_TRANSCRIPT_PROCESSING,
    GIT_COMMIT_PROCESSING,
    DOCUMENTATION_PROCESSING,
    CLASS_SUMMARY,
    METHOD_SUMMARY,
    AGENT_TOOL_SUFFIX,
}
