# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/correction/correction.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/correction/correction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"jervis/correction/correction.proto\x12\x11jervis.correction\x1a\x19jervis/common/types.proto\"R\n\x11\x43orrectionRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x11\n\tbody_json\x18\x02 \x01(\t\"7\n\x12\x43orrectionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x11\n\tbody_json\x18\x02 \x01(\t2\xc8\x05\n\x11\x43orrectionService\x12_\n\x10SubmitCorrection\x12$.jervis.correction.CorrectionRequest\x1a%.jervis.correction.CorrectionResponse\x12`\n\x11\x43orrectTranscript\x12$.jervis.correction.CorrectionRequest\x1a%.jervis.correction.CorrectionResponse\x12^\n\x0fListCorrections\x12$.jervis.correction.CorrectionRequest\x1a%.jervis.correction.CorrectionResponse\x12h\n\x19\x41nswerCorrectionQuestions\x12$.jervis.correction.CorrectionRequest\x1a%.jervis.correction.CorrectionResponse\x12\x65\n\x16\x43orrectWithInstruction\x12$.jervis.correction.CorrectionRequest\x1a%.jervis.correction.CorrectionResponse\x12^\n\x0f\x43orrectTargeted\x12$.jervis.correction.CorrectionRequest\x1a%.jervis.correction.CorrectionResponse\x12_\n\x10\x44\x65leteCorrection\x12$.jervis.correction.CorrectionRequest\x1a%.jervis.correction.CorrectionResponseB4\n\x1f\x63om.jervis.contracts.correctionB\x0f\x43orrectionProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.correction.correction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037com.jervis.contracts.correctionB\017CorrectionProtoP\001'
  _globals['_CORRECTIONREQUEST']._serialized_start=84
  _globals['_CORRECTIONREQUEST']._serialized_end=166
  _globals['_CORRECTIONRESPONSE']._serialized_start=168
  _globals['_CORRECTIONRESPONSE']._serialized_end=223
  _globals['_CORRECTIONSERVICE']._serialized_start=226
  _globals['_CORRECTIONSERVICE']._serialized_end=938
# @@protoc_insertion_point(module_scope)
