# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/tts/speak.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/tts/speak.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16jervis/tts/speak.proto\x12\njervis.tts\x1a\x19jervis/common/types.proto\"x\n\x0cSpeakRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05voice\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\x01\x12\x10\n\x08language\x18\x05 \x01(\t\"F\n\rSpeakResponse\x12\x0b\n\x03wav\x18\x01 \x01(\x0c\x12\x13\n\x0b\x64uration_ms\x18\x02 \x01(\x03\x12\x13\n\x0btext_length\x18\x03 \x01(\x05\"+\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\x32\x8d\x01\n\nTtsService\x12<\n\x05Speak\x12\x18.jervis.tts.SpeakRequest\x1a\x19.jervis.tts.SpeakResponse\x12\x41\n\x0bSpeakStream\x12\x18.jervis.tts.SpeakRequest\x1a\x16.jervis.tts.AudioChunk0\x01\x42&\n\x18\x63om.jervis.contracts.ttsB\x08TtsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.tts.speak_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.jervis.contracts.ttsB\010TtsProtoP\001'
  _globals['_SPEAKREQUEST']._serialized_start=65
  _globals['_SPEAKREQUEST']._serialized_end=185
  _globals['_SPEAKRESPONSE']._serialized_start=187
  _globals['_SPEAKRESPONSE']._serialized_end=257
  _globals['_AUDIOCHUNK']._serialized_start=259
  _globals['_AUDIOCHUNK']._serialized_end=302
  _globals['_TTSSERVICE']._serialized_start=305
  _globals['_TTSSERVICE']._serialized_end=446
# @@protoc_insertion_point(module_scope)
