# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.router import admin_pb2 as jervis_dot_router_dot_admin__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/router/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouterAdminServiceStub(object):
    """RouterAdminService exposes the `/router/admin/*` and
    `/router/internal/*` surface of `service-ollama-router`. The transparent
    Ollama-compatible endpoints (`/api/generate`, `/api/chat`, `/api/embeddings`)
    stay REST because they are a vendor contract (Ollama API) — consumers
    call them directly, no gRPC wrapper.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMaxContext = channel.unary_unary(
                '/jervis.router.RouterAdminService/GetMaxContext',
                request_serializer=jervis_dot_router_dot_admin__pb2.MaxContextRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.MaxContextResponse.FromString,
                _registered_method=True)
        self.ReportModelError = channel.unary_unary(
                '/jervis.router.RouterAdminService/ReportModelError',
                request_serializer=jervis_dot_router_dot_admin__pb2.ReportModelErrorRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.ReportModelErrorResponse.FromString,
                _registered_method=True)
        self.ReportModelSuccess = channel.unary_unary(
                '/jervis.router.RouterAdminService/ReportModelSuccess',
                request_serializer=jervis_dot_router_dot_admin__pb2.ReportModelSuccessRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.ReportModelSuccessResponse.FromString,
                _registered_method=True)
        self.ListModelErrors = channel.unary_unary(
                '/jervis.router.RouterAdminService/ListModelErrors',
                request_serializer=jervis_dot_router_dot_admin__pb2.ListModelErrorsRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.ListModelErrorsResponse.FromString,
                _registered_method=True)
        self.ListModelStats = channel.unary_unary(
                '/jervis.router.RouterAdminService/ListModelStats',
                request_serializer=jervis_dot_router_dot_admin__pb2.ListModelStatsRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.ListModelStatsResponse.FromString,
                _registered_method=True)
        self.ResetModelError = channel.unary_unary(
                '/jervis.router.RouterAdminService/ResetModelError',
                request_serializer=jervis_dot_router_dot_admin__pb2.ResetModelErrorRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.ResetModelErrorResponse.FromString,
                _registered_method=True)
        self.TestModel = channel.unary_unary(
                '/jervis.router.RouterAdminService/TestModel',
                request_serializer=jervis_dot_router_dot_admin__pb2.TestModelRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.TestModelResponse.FromString,
                _registered_method=True)
        self.GetRateLimits = channel.unary_unary(
                '/jervis.router.RouterAdminService/GetRateLimits',
                request_serializer=jervis_dot_router_dot_admin__pb2.RateLimitsRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.RateLimitsResponse.FromString,
                _registered_method=True)
        self.InvalidateClientTier = channel.unary_unary(
                '/jervis.router.RouterAdminService/InvalidateClientTier',
                request_serializer=jervis_dot_router_dot_admin__pb2.InvalidateClientTierRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.InvalidateClientTierResponse.FromString,
                _registered_method=True)
        self.WhisperNotify = channel.unary_unary(
                '/jervis.router.RouterAdminService/WhisperNotify',
                request_serializer=jervis_dot_router_dot_admin__pb2.WhisperNotifyRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.WhisperNotifyResponse.FromString,
                _registered_method=True)
        self.WhisperDone = channel.unary_unary(
                '/jervis.router.RouterAdminService/WhisperDone',
                request_serializer=jervis_dot_router_dot_admin__pb2.WhisperDoneRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.WhisperDoneResponse.FromString,
                _registered_method=True)
        self.TtsNotify = channel.unary_unary(
                '/jervis.router.RouterAdminService/TtsNotify',
                request_serializer=jervis_dot_router_dot_admin__pb2.TtsNotifyRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.TtsNotifyResponse.FromString,
                _registered_method=True)
        self.TtsDone = channel.unary_unary(
                '/jervis.router.RouterAdminService/TtsDone',
                request_serializer=jervis_dot_router_dot_admin__pb2.TtsDoneRequest.SerializeToString,
                response_deserializer=jervis_dot_router_dot_admin__pb2.TtsDoneResponse.FromString,
                _registered_method=True)


class RouterAdminServiceServicer(object):
    """RouterAdminService exposes the `/router/admin/*` and
    `/router/internal/*` surface of `service-ollama-router`. The transparent
    Ollama-compatible endpoints (`/api/generate`, `/api/chat`, `/api/embeddings`)
    stay REST because they are a vendor contract (Ollama API) — consumers
    call them directly, no gRPC wrapper.
    """

    def GetMaxContext(self, request, context):
        """Max available context tokens for a given TierCap (used by the
        orchestrator's context budgeter).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportModelError(self, request, context):
        """Report a provider error (400/500) so the router can disable the model
        after N consecutive failures.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportModelSuccess(self, request, context):
        """Report a successful call — resets error counter and records stats.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModelErrors(self, request, context):
        """Snapshot of model error state — keyed by model_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModelStats(self, request, context):
        """Snapshot of usage statistics for every tracked model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetModelError(self, request, context):
        """Re-enable a previously-disabled model (UI action after manual testing).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestModel(self, request, context):
        """Send a tiny completion to an OpenRouter model to verify it responds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRateLimits(self, request, context):
        """OpenRouter rate-limit status per queue (FREE / PAID / PREMIUM).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateClientTier(self, request, context):
        """Invalidate the router's cached client tier after cloudModelPolicy
        changes on the Kotlin server. Empty client_id = invalidate all.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhisperNotify(self, request, context):
        """Whisper on VD signals it wants GPU for transcription. The router
        preempts every active Ollama LLM/VLM request (embeddings stay —
        they're tiny and fast), unloads those models to free VRAM, and
        re-enqueues the preempted requests so they resume automatically
        after WhisperDone. XTTS is a permanent resident and is never
        touched. Returns once Ollama has been quiesced (or on timeout).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhisperDone(self, request, context):
        """Whisper signals transcription is complete — router releases the
        semaphore and the dispatcher fires waiting queue entries.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TtsNotify(self, request, context):
        """XTTS on VD signals it wants exclusive GPU for synthesis. Same active
        preemption flow as WhisperNotify: cancel Ollama LLM/VLM, unload
        their models, block until quiet. User contract:
        "during whisper streaming AND during XTTS generation nothing else
        runs on the GPU"
        Embeddings are also dropped here — the caller is a user-facing audio
        stream, every idle millisecond shows up as an audible gap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TtsDone(self, request, context):
        """XTTS signals synthesis finished — router clears the semaphore and
        Ollama dispatcher resumes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMaxContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaxContext,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.MaxContextRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.MaxContextResponse.SerializeToString,
            ),
            'ReportModelError': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportModelError,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.ReportModelErrorRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.ReportModelErrorResponse.SerializeToString,
            ),
            'ReportModelSuccess': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportModelSuccess,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.ReportModelSuccessRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.ReportModelSuccessResponse.SerializeToString,
            ),
            'ListModelErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelErrors,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.ListModelErrorsRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.ListModelErrorsResponse.SerializeToString,
            ),
            'ListModelStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelStats,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.ListModelStatsRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.ListModelStatsResponse.SerializeToString,
            ),
            'ResetModelError': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetModelError,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.ResetModelErrorRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.ResetModelErrorResponse.SerializeToString,
            ),
            'TestModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TestModel,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.TestModelRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.TestModelResponse.SerializeToString,
            ),
            'GetRateLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRateLimits,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.RateLimitsRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.RateLimitsResponse.SerializeToString,
            ),
            'InvalidateClientTier': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateClientTier,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.InvalidateClientTierRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.InvalidateClientTierResponse.SerializeToString,
            ),
            'WhisperNotify': grpc.unary_unary_rpc_method_handler(
                    servicer.WhisperNotify,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.WhisperNotifyRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.WhisperNotifyResponse.SerializeToString,
            ),
            'WhisperDone': grpc.unary_unary_rpc_method_handler(
                    servicer.WhisperDone,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.WhisperDoneRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.WhisperDoneResponse.SerializeToString,
            ),
            'TtsNotify': grpc.unary_unary_rpc_method_handler(
                    servicer.TtsNotify,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.TtsNotifyRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.TtsNotifyResponse.SerializeToString,
            ),
            'TtsDone': grpc.unary_unary_rpc_method_handler(
                    servicer.TtsDone,
                    request_deserializer=jervis_dot_router_dot_admin__pb2.TtsDoneRequest.FromString,
                    response_serializer=jervis_dot_router_dot_admin__pb2.TtsDoneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.router.RouterAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.router.RouterAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterAdminService(object):
    """RouterAdminService exposes the `/router/admin/*` and
    `/router/internal/*` surface of `service-ollama-router`. The transparent
    Ollama-compatible endpoints (`/api/generate`, `/api/chat`, `/api/embeddings`)
    stay REST because they are a vendor contract (Ollama API) — consumers
    call them directly, no gRPC wrapper.
    """

    @staticmethod
    def GetMaxContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/GetMaxContext',
            jervis_dot_router_dot_admin__pb2.MaxContextRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.MaxContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportModelError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/ReportModelError',
            jervis_dot_router_dot_admin__pb2.ReportModelErrorRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.ReportModelErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportModelSuccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/ReportModelSuccess',
            jervis_dot_router_dot_admin__pb2.ReportModelSuccessRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.ReportModelSuccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModelErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/ListModelErrors',
            jervis_dot_router_dot_admin__pb2.ListModelErrorsRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.ListModelErrorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModelStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/ListModelStats',
            jervis_dot_router_dot_admin__pb2.ListModelStatsRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.ListModelStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetModelError(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/ResetModelError',
            jervis_dot_router_dot_admin__pb2.ResetModelErrorRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.ResetModelErrorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/TestModel',
            jervis_dot_router_dot_admin__pb2.TestModelRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.TestModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRateLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/GetRateLimits',
            jervis_dot_router_dot_admin__pb2.RateLimitsRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.RateLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateClientTier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/InvalidateClientTier',
            jervis_dot_router_dot_admin__pb2.InvalidateClientTierRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.InvalidateClientTierResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WhisperNotify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/WhisperNotify',
            jervis_dot_router_dot_admin__pb2.WhisperNotifyRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.WhisperNotifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WhisperDone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/WhisperDone',
            jervis_dot_router_dot_admin__pb2.WhisperDoneRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.WhisperDoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TtsNotify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/TtsNotify',
            jervis_dot_router_dot_admin__pb2.TtsNotifyRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.TtsNotifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TtsDone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.router.RouterAdminService/TtsDone',
            jervis_dot_router_dot_admin__pb2.TtsDoneRequest.SerializeToString,
            jervis_dot_router_dot_admin__pb2.TtsDoneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
