# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.whatsapp_browser import whatsapp_pb2 as jervis_dot_whatsapp__browser_dot_whatsapp__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/whatsapp_browser/whatsapp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WhatsAppBrowserServiceStub(object):
    """WhatsAppBrowserService — typed wrapper over the jervis-whatsapp-browser
    pod. Replaces the former REST surface consumed by the Kotlin server
    (/session/{cid}, /session/{cid}/init, /scrape/{cid}/trigger,
    /scrape/{cid}/latest, /vnc-token/{cid}). The VNC proxy routes
    (/vnc-login, /vnc-auth) stay HTTP — browser-facing, not pod-to-pod.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSession = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/GetSession',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionRef.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionStatus.FromString,
                _registered_method=True)
        self.InitSession = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/InitSession',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.InitSessionRequest.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.InitSessionResponse.FromString,
                _registered_method=True)
        self.TriggerScrape = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/TriggerScrape',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.TriggerScrapeRequest.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.TriggerScrapeResponse.FromString,
                _registered_method=True)
        self.GetLatestScrape = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/GetLatestScrape',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionRef.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.LatestScrapeResponse.FromString,
                _registered_method=True)
        self.CreateVncToken = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/CreateVncToken',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionRef.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.VncTokenResponse.FromString,
                _registered_method=True)


class WhatsAppBrowserServiceServicer(object):
    """WhatsAppBrowserService — typed wrapper over the jervis-whatsapp-browser
    pod. Replaces the former REST surface consumed by the Kotlin server
    (/session/{cid}, /session/{cid}/init, /scrape/{cid}/trigger,
    /scrape/{cid}/latest, /vnc-token/{cid}). The VNC proxy routes
    (/vnc-login, /vnc-auth) stay HTTP — browser-facing, not pod-to-pod.
    """

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerScrape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestScrape(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVncToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhatsAppBrowserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionRef.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionStatus.SerializeToString,
            ),
            'InitSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InitSession,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.InitSessionRequest.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.InitSessionResponse.SerializeToString,
            ),
            'TriggerScrape': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerScrape,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.TriggerScrapeRequest.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.TriggerScrapeResponse.SerializeToString,
            ),
            'GetLatestScrape': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestScrape,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionRef.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.LatestScrapeResponse.SerializeToString,
            ),
            'CreateVncToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVncToken,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionRef.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.VncTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.whatsapp_browser.WhatsAppBrowserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.whatsapp_browser.WhatsAppBrowserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WhatsAppBrowserService(object):
    """WhatsAppBrowserService — typed wrapper over the jervis-whatsapp-browser
    pod. Replaces the former REST surface consumed by the Kotlin server
    (/session/{cid}, /session/{cid}/init, /scrape/{cid}/trigger,
    /scrape/{cid}/latest, /vnc-token/{cid}). The VNC proxy routes
    (/vnc-login, /vnc-auth) stay HTTP — browser-facing, not pod-to-pod.
    """

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/GetSession',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionRef.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/InitSession',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.InitSessionRequest.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.InitSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerScrape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/TriggerScrape',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.TriggerScrapeRequest.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.TriggerScrapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestScrape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/GetLatestScrape',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionRef.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.LatestScrapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVncToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/CreateVncToken',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.SessionRef.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.VncTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
