# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.whatsapp_browser import whatsapp_pb2 as jervis_dot_whatsapp__browser_dot_whatsapp__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/whatsapp_browser/whatsapp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WhatsAppBrowserServiceStub(object):
    """WhatsAppBrowserService — gRPC wrapper on top of the `jervis-whatsapp-browser`
    pod. Kotlin server's ConnectionRpcImpl + WhatsAppPollingHandler dial
    these RPCs instead of the former REST surface
    (/session/{cid}, /session/{cid}/init, /scrape/{cid}/trigger,
    /scrape/{cid}/latest, /vnc-token/{cid}). The VNC proxy routes
    (/vnc-login, /vnc-auth) stay HTTP — they're browser-facing.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SessionStatus = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/SessionStatus',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
                _registered_method=True)
        self.SessionInit = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/SessionInit',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
                _registered_method=True)
        self.ScrapeTrigger = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/ScrapeTrigger',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
                _registered_method=True)
        self.ScrapeLatest = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/ScrapeLatest',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
                _registered_method=True)
        self.VncToken = channel.unary_unary(
                '/jervis.whatsapp_browser.WhatsAppBrowserService/VncToken',
                request_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
                response_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
                _registered_method=True)


class WhatsAppBrowserServiceServicer(object):
    """WhatsAppBrowserService — gRPC wrapper on top of the `jervis-whatsapp-browser`
    pod. Kotlin server's ConnectionRpcImpl + WhatsAppPollingHandler dial
    these RPCs instead of the former REST surface
    (/session/{cid}, /session/{cid}/init, /scrape/{cid}/trigger,
    /scrape/{cid}/latest, /vnc-token/{cid}). The VNC proxy routes
    (/vnc-login, /vnc-auth) stay HTTP — they're browser-facing.
    """

    def SessionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SessionInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScrapeTrigger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScrapeLatest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VncToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhatsAppBrowserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionStatus,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.SerializeToString,
            ),
            'SessionInit': grpc.unary_unary_rpc_method_handler(
                    servicer.SessionInit,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.SerializeToString,
            ),
            'ScrapeTrigger': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrapeTrigger,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.SerializeToString,
            ),
            'ScrapeLatest': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrapeLatest,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.SerializeToString,
            ),
            'VncToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VncToken,
                    request_deserializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.FromString,
                    response_serializer=jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.whatsapp_browser.WhatsAppBrowserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.whatsapp_browser.WhatsAppBrowserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WhatsAppBrowserService(object):
    """WhatsAppBrowserService — gRPC wrapper on top of the `jervis-whatsapp-browser`
    pod. Kotlin server's ConnectionRpcImpl + WhatsAppPollingHandler dial
    these RPCs instead of the former REST surface
    (/session/{cid}, /session/{cid}/init, /scrape/{cid}/trigger,
    /scrape/{cid}/latest, /vnc-token/{cid}). The VNC proxy routes
    (/vnc-login, /vnc-auth) stay HTTP — they're browser-facing.
    """

    @staticmethod
    def SessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/SessionStatus',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SessionInit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/SessionInit',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScrapeTrigger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/ScrapeTrigger',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScrapeLatest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/ScrapeLatest',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VncToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.whatsapp_browser.WhatsAppBrowserService/VncToken',
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.WhatsAppRequest.SerializeToString,
            jervis_dot_whatsapp__browser_dot_whatsapp__pb2.RawResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
