# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jervis.o365_gateway import gateway_pb2 as jervis_dot_o365__gateway_dot_gateway__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jervis/o365_gateway/gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class O365GatewayServiceStub(object):
    """O365GatewayService — one umbrella gRPC for the O365 gateway pod. It
    fronts every Microsoft Graph call Jervis makes (Teams chats / channels,
    Mail, Calendar, Online meetings, Drive, session). Graph-specific DTOs
    are shared across RPC groups so the same `ChatMessage` is returned for
    Teams chats and channel reads.

    Typed RPCs land incrementally (slice V5a -> Teams chats, V5b -> channels,
    etc.). The legacy Request / RequestBytes passthrough stays until every
    group is typed; it is dropped in V5h.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Request = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/Request',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.O365Request.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.O365Response.FromString,
                _registered_method=True)
        self.RequestBytes = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/RequestBytes',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.O365Request.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.O365BytesResponse.FromString,
                _registered_method=True)
        self.ListChats = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ListChats',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChatsRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChatsResponse.FromString,
                _registered_method=True)
        self.ReadChat = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ReadChat',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ReadChatRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChatMessagesResponse.FromString,
                _registered_method=True)
        self.SendChatMessage = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/SendChatMessage',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.SendChatMessageRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.ListTeams = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ListTeams',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListTeamsRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListTeamsResponse.FromString,
                _registered_method=True)
        self.ListChannels = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ListChannels',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChannelsRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChannelsResponse.FromString,
                _registered_method=True)
        self.ReadChannel = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ReadChannel',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ReadChannelRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChannelMessagesResponse.FromString,
                _registered_method=True)
        self.SendChannelMessage = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/SendChannelMessage',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.SendChannelMessageRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.ListMail = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ListMail',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListMailRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListMailResponse.FromString,
                _registered_method=True)
        self.ReadMail = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ReadMail',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ReadMailRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.MailMessage.FromString,
                _registered_method=True)
        self.SendMail = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/SendMail',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.SendMailRpcRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.SendMailAck.FromString,
                _registered_method=True)
        self.ListCalendarEvents = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ListCalendarEvents',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListCalendarEventsRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListCalendarEventsResponse.FromString,
                _registered_method=True)
        self.CreateCalendarEvent = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/CreateCalendarEvent',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.CreateCalendarEventRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.CalendarEvent.FromString,
                _registered_method=True)
        self.GetOnlineMeetingByJoinUrl = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/GetOnlineMeetingByJoinUrl',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingByJoinUrlRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeeting.FromString,
                _registered_method=True)
        self.GetOnlineMeeting = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/GetOnlineMeeting',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeeting.FromString,
                _registered_method=True)
        self.ListMeetingRecordings = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ListMeetingRecordings',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListRecordingsResponse.FromString,
                _registered_method=True)
        self.ListMeetingTranscripts = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/ListMeetingTranscripts',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingRequest.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListTranscriptsResponse.FromString,
                _registered_method=True)
        self.DownloadTranscriptVtt = channel.unary_unary(
                '/jervis.o365_gateway.O365GatewayService/DownloadTranscriptVtt',
                request_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.TranscriptRef.SerializeToString,
                response_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.TranscriptContent.FromString,
                _registered_method=True)


class O365GatewayServiceServicer(object):
    """O365GatewayService — one umbrella gRPC for the O365 gateway pod. It
    fronts every Microsoft Graph call Jervis makes (Teams chats / channels,
    Mail, Calendar, Online meetings, Drive, session). Graph-specific DTOs
    are shared across RPC groups so the same `ChatMessage` is returned for
    Teams chats and channel reads.

    Typed RPCs land incrementally (slice V5a -> Teams chats, V5b -> channels,
    etc.). The legacy Request / RequestBytes passthrough stays until every
    group is typed; it is dropped in V5h.
    """

    def Request(self, request, context):
        """=== Legacy passthrough (drop at V5h) =====================================
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestBytes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChats(self, request, context):
        """=== V5a - Teams chats ====================================================
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChatMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeams(self, request, context):
        """=== V5b - Teams teams / channels =========================================
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChannelMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMail(self, request, context):
        """=== V5c - Mail (Outlook) =================================================
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCalendarEvents(self, request, context):
        """=== V5d - Calendar =======================================================
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCalendarEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOnlineMeetingByJoinUrl(self, request, context):
        """=== V5e - Online meetings ================================================
        Part of the O365 umbrella: online meetings are a resource inside O365,
        not a separate service. All five RPCs live here so consumers dial one
        channel for everything meeting-related.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOnlineMeeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMeetingRecordings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMeetingTranscripts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadTranscriptVtt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_O365GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Request': grpc.unary_unary_rpc_method_handler(
                    servicer.Request,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.O365Request.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.O365Response.SerializeToString,
            ),
            'RequestBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestBytes,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.O365Request.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.O365BytesResponse.SerializeToString,
            ),
            'ListChats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChats,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChatsRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChatsResponse.SerializeToString,
            ),
            'ReadChat': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadChat,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ReadChatRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChatMessagesResponse.SerializeToString,
            ),
            'SendChatMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChatMessage,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.SendChatMessageRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ChatMessage.SerializeToString,
            ),
            'ListTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTeams,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListTeamsRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListTeamsResponse.SerializeToString,
            ),
            'ListChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChannels,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChannelsRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChannelsResponse.SerializeToString,
            ),
            'ReadChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadChannel,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ReadChannelRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListChannelMessagesResponse.SerializeToString,
            ),
            'SendChannelMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChannelMessage,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.SendChannelMessageRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ChatMessage.SerializeToString,
            ),
            'ListMail': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMail,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListMailRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListMailResponse.SerializeToString,
            ),
            'ReadMail': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadMail,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ReadMailRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.MailMessage.SerializeToString,
            ),
            'SendMail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMail,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.SendMailRpcRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.SendMailAck.SerializeToString,
            ),
            'ListCalendarEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCalendarEvents,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListCalendarEventsRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListCalendarEventsResponse.SerializeToString,
            ),
            'CreateCalendarEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCalendarEvent,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.CreateCalendarEventRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.CalendarEvent.SerializeToString,
            ),
            'GetOnlineMeetingByJoinUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOnlineMeetingByJoinUrl,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingByJoinUrlRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeeting.SerializeToString,
            ),
            'GetOnlineMeeting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOnlineMeeting,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeeting.SerializeToString,
            ),
            'ListMeetingRecordings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMeetingRecordings,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListRecordingsResponse.SerializeToString,
            ),
            'ListMeetingTranscripts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMeetingTranscripts,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingRequest.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.ListTranscriptsResponse.SerializeToString,
            ),
            'DownloadTranscriptVtt': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadTranscriptVtt,
                    request_deserializer=jervis_dot_o365__gateway_dot_gateway__pb2.TranscriptRef.FromString,
                    response_serializer=jervis_dot_o365__gateway_dot_gateway__pb2.TranscriptContent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jervis.o365_gateway.O365GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jervis.o365_gateway.O365GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class O365GatewayService(object):
    """O365GatewayService — one umbrella gRPC for the O365 gateway pod. It
    fronts every Microsoft Graph call Jervis makes (Teams chats / channels,
    Mail, Calendar, Online meetings, Drive, session). Graph-specific DTOs
    are shared across RPC groups so the same `ChatMessage` is returned for
    Teams chats and channel reads.

    Typed RPCs land incrementally (slice V5a -> Teams chats, V5b -> channels,
    etc.). The legacy Request / RequestBytes passthrough stays until every
    group is typed; it is dropped in V5h.
    """

    @staticmethod
    def Request(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/Request',
            jervis_dot_o365__gateway_dot_gateway__pb2.O365Request.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.O365Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/RequestBytes',
            jervis_dot_o365__gateway_dot_gateway__pb2.O365Request.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.O365BytesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ListChats',
            jervis_dot_o365__gateway_dot_gateway__pb2.ListChatsRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ListChatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ReadChat',
            jervis_dot_o365__gateway_dot_gateway__pb2.ReadChatRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ListChatMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/SendChatMessage',
            jervis_dot_o365__gateway_dot_gateway__pb2.SendChatMessageRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ListTeams',
            jervis_dot_o365__gateway_dot_gateway__pb2.ListTeamsRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ListTeamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ListChannels',
            jervis_dot_o365__gateway_dot_gateway__pb2.ListChannelsRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ListChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ReadChannel',
            jervis_dot_o365__gateway_dot_gateway__pb2.ReadChannelRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ListChannelMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendChannelMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/SendChannelMessage',
            jervis_dot_o365__gateway_dot_gateway__pb2.SendChannelMessageRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ListMail',
            jervis_dot_o365__gateway_dot_gateway__pb2.ListMailRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ListMailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadMail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ReadMail',
            jervis_dot_o365__gateway_dot_gateway__pb2.ReadMailRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.MailMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/SendMail',
            jervis_dot_o365__gateway_dot_gateway__pb2.SendMailRpcRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.SendMailAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCalendarEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ListCalendarEvents',
            jervis_dot_o365__gateway_dot_gateway__pb2.ListCalendarEventsRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ListCalendarEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCalendarEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/CreateCalendarEvent',
            jervis_dot_o365__gateway_dot_gateway__pb2.CreateCalendarEventRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.CalendarEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOnlineMeetingByJoinUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/GetOnlineMeetingByJoinUrl',
            jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingByJoinUrlRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeeting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOnlineMeeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/GetOnlineMeeting',
            jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeeting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMeetingRecordings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ListMeetingRecordings',
            jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ListRecordingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMeetingTranscripts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/ListMeetingTranscripts',
            jervis_dot_o365__gateway_dot_gateway__pb2.OnlineMeetingRequest.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.ListTranscriptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadTranscriptVtt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jervis.o365_gateway.O365GatewayService/DownloadTranscriptVtt',
            jervis_dot_o365__gateway_dot_gateway__pb2.TranscriptRef.SerializeToString,
            jervis_dot_o365__gateway_dot_gateway__pb2.TranscriptContent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
