# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jervis/meeting_attender/attender.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jervis/meeting_attender/attender.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jervis.common import types_pb2 as jervis_dot_common_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&jervis/meeting_attender/attender.proto\x12\x17jervis.meeting_attender\x1a\x19jervis/common/types.proto\"\xbc\x01\n\rAttendRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t\x12\x12\n\nproject_id\x18\x04 \x01(\t\x12\r\n\x05title\x18\x05 \x01(\t\x12\x10\n\x08join_url\x18\x06 \x01(\t\x12\x14\n\x0c\x65nd_time_iso\x18\x07 \x01(\t\x12\x10\n\x08provider\x18\x08 \x01(\t\"K\n\x0e\x41ttendResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"Z\n\x0bStopRequest\x12*\n\x03\x63tx\x18\x01 \x01(\x0b\x32\x1d.jervis.common.RequestContext\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\")\n\x0cStopResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xc8\x01\n\x16MeetingAttenderService\x12Y\n\x06\x41ttend\x12&.jervis.meeting_attender.AttendRequest\x1a\'.jervis.meeting_attender.AttendResponse\x12S\n\x04Stop\x12$.jervis.meeting_attender.StopRequest\x1a%.jervis.meeting_attender.StopResponseB?\n%com.jervis.contracts.meeting_attenderB\x14MeetingAttenderProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jervis.meeting_attender.attender_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n%com.jervis.contracts.meeting_attenderB\024MeetingAttenderProtoP\001'
  _globals['_ATTENDREQUEST']._serialized_start=95
  _globals['_ATTENDREQUEST']._serialized_end=283
  _globals['_ATTENDRESPONSE']._serialized_start=285
  _globals['_ATTENDRESPONSE']._serialized_end=360
  _globals['_STOPREQUEST']._serialized_start=362
  _globals['_STOPREQUEST']._serialized_end=452
  _globals['_STOPRESPONSE']._serialized_start=454
  _globals['_STOPRESPONSE']._serialized_end=495
  _globals['_MEETINGATTENDERSERVICE']._serialized_start=498
  _globals['_MEETINGATTENDERSERVICE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
